### ISSUE TITLE
feat: eth_getTransactionCount

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#101]
# eth_getTransactionCount

- name: getTransactionCount
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis)

## Specification Description

Requests a specific account's number of transactions, in order to compute its nonce.

### Parameters

- Address
- Block

### Returns

- uint256 - e.g. Transaction Count

## Kakarot Logic

Call the Starknet `starknet_getNonce` json rpc method. Return it.

**Comment by internnos** [comment]
hi i'd like to take this issue!

**Comment by Eikix** [comment]
hey @internnos ! happy to see you here,

I believe the correct way to go about this issue is to grab the nonce of a particular starknet address using the starknet-rpc endpoint.

you can draw inspiration from the current architecture and other methods. but essentially:

1. grab the ethereum address received, and ask Kakarot to compute the corresponding starknet address (using compute_starknet_address)
2. call the starknet rpc method get_nonce https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L629
3. return the correctly formed payload (as per the spec) https://ethereum.github.io/execution-apis/api-documentation/

**Comment by internnos** [comment]
i have a question @Eikix 

according to [this](https://github.com/sayajin-labs/kakarot-rpc/blob/4335777ae694db799b2c9bcc5ec0b041ba1fa0c6/core/src/client/client_api.rs#L78) the signature of `compute_starknet_address` needs `starknet_block_id`

however, during the computation of `transaction_count`, `ethereum_block_id` is not required 

https://ethereum.github.io/execution-apis/api-documentation/
<img width="1304" alt="Screenshot 2023-04-08 at 2 01 05 pm" src="https://user-images.githubusercontent.com/26416205/230708155-048f1d98-688a-46cc-865c-8e709b6f229b.png">

 but when i tried without the `ethereum_block_id`, i got the following error
 
 ```
 {
    "jsonrpc": "2.0",
    "id": 0,
    "error": {
        "code": -32602,
        "message": "missing value for required argument 1"
    }
}
```

does it mean that the ethereum spec docs is incorrect in this part?

**Comment by ClementWalter** [comment]
hey @internnos , so I used the https://composer.alchemy.com/ tool to make a smol test and this param is actually *not* required, see corresponding curl request

```
$ curl 'https://eth-mainnet.g.alchemy.com/v2/18lHSAeZttzI4wJvHpXlJGHK4ZDNCTCP' \
  -H 'content-type: application/json' \
  --data-raw '{"jsonrpc":"2.0","id":0,"method":"eth_getTransactionCount","params":["0xabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"]}' \
  --compressed

{"jsonrpc":"2.0","id":0,"result":"0x0"}%
```

which means that we should handle this in the RPC as well. Not providing the block means `"latest"` btw

**Comment by internnos** [comment]
> hey @internnos , so I used the https://composer.alchemy.com/ tool to make a smol test and this param is actually _not_ required, see corresponding curl request
> 
> ```
> $ curl 'https://eth-mainnet.g.alchemy.com/v2/18lHSAeZttzI4wJvHpXlJGHK4ZDNCTCP' \
>   -H 'content-type: application/json' \
>   --data-raw '{"jsonrpc":"2.0","id":0,"method":"eth_getTransactionCount","params":["0xabcdabcdabcdabcdabcdabcdabcdabcdabcdabcd"]}' \
>   --compressed
> 
> {"jsonrpc":"2.0","id":0,"result":"0x0"}%
> ```
> 
> which means that we should handle this in the RPC as well. Not providing the block means `"latest"` btw

aah thanks for the clarity. all clear now, thanks @ClementWalter!
