### ISSUE TITLE
dev: add a `usage` rule in the makefile

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1031]
**Describe the enhancement request**

In order to add some kind of documentation on the usage of the makefile, add a `usage` rule to it which echos documentation about each available rule in the makefile. Here is a link to an example: https://github.com/lambdaclass/cairo_native/blob/main/Makefile#L25

**Comment by Gerson2102** [comment]
Hello. Can I work on this one?
