### ISSUE TITLE
exploration: fork and deploy starkgate for kakarot testnet

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1043]
# Feature Request

**Describe the Feature Request**

We're ready to incorporate a bridge into our stack

**Describe Preferred Solution**
Blocked by:
Sync with SW during an engineering kick-off call. Understand what we need to do as a Starknet appchain to enable the bridge between L1 sepolia and kakarot.

repo:
https://github.com/starknet-io/starkgate-contracts/tree/cairo-1

doc:
https://docs.starknet.io/documentation/tools/starkgate-bridge/

**Comment by tcoratger** [comment]
@Eikix seems not to be relevant anymore no?
