### ISSUE TITLE
bug: update `trace_block` function to use correct basefee

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1047]
# Bug Report

**Kakarot RPC version:**

**Current behavior:**
During the tracing in `trace_block`, the function computes the basefee of the block with the below code:
https://github.com/kkrt-labs/kakarot-rpc/blob/ef85ab965bd22abc425e47a143da8df36f50252f/src/tracing/mod.rs#L60-L67

This is however incorrect as the basefee of the block should just be used instead. This basefee can be extracted from the `env` value.

**Expected behavior:**
Correct block base fee should be used.

**Comment by edisontim** [comment]
Gm, can I have this one?
