### ISSUE TITLE
Increase the gas estimate returned by `estimate_gas_helper` by 20%.

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1052]

**Comment by Gerson2102** [comment]
The description for this issue i guess is the linked issue.

**Comment by greged93** [comment]
Indeed, it's really just about increasing by 20% the return value

**Comment by Gerson2102** [comment]
Please assign this to me. I'll see if i can handle it.

**Comment by iabhi4** [comment]
I can check this
