### ISSUE TITLE
feat: document the use of constants in `src/eth_provider/constant.rs`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1054]
# Feature Request

**Describe the Feature Request**
We have a couple of constants in `src/eth_provider/constant.rs` which could use some documentation.
https://github.com/kkrt-labs/kakarot-rpc/blob/ef85ab965bd22abc425e47a143da8df36f50252f/src/eth_provider/constant.rs#L8-L13

**Comment by edisontim** [comment]
Could I take this?
