### ISSUE TITLE
dev: use `From` to transform `Transaction` to `TransactionInfo` 

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1058]
**Describe the enhancement request**

After https://github.com/alloy-rs/alloy/pull/662 is integrated into the next release of reth, parts of our codebase where a transformation is made from a `Transaction` type to a `TransactionInfo` type such as 

https://github.com/kkrt-labs/kakarot-rpc/blob/0f68f26e6aa4c0db68e9fccb5bc8869efbff7749/src/tracing/mod.rs#L68-L74

can be refactored using `From` implementation.

**Comment by Gerson2102** [comment]
Hello. Can you assign this to me?

**Comment by tcoratger** [comment]
> Hello. Can you assign this to me?

Assigned

**Comment by Gerson2102** [comment]
@tcoratger hello sir. How can I see if that from function is integrated into the next release of reth, to work in this issue?

**Comment by tcoratger** [comment]
Hey, at the moment we still are working with the last reth version https://github.com/paradigmxyz/reth/tree/v0.2.0-beta.6 where this is not integrated. Will ping you here once:
- The new release is out
- And I've integrated this bump into our codebase

**Comment by tcoratger** [comment]
@Gerson2102 For your information https://github.com/kkrt-labs/kakarot-rpc/pull/1065 should unlock your work here

**Comment by Gerson2102** [comment]
@tcoratger got it sir. thanks.
