### ISSUE TITLE
dev: use `with_base_fee` for `TransactionInfo`

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1069]
**Describe the enhancement request**

When https://github.com/alloy-rs/alloy/pull/721 is included in the next release of reth (blocker at the moment), these lines https://github.com/kkrt-labs/kakarot-rpc/blob/338323ff8bd338bc4515f03065d79314e1850aaa/src/tracing/mod.rs#L68-L69 could be merged into a single one using the dedicated `with_base_fee` method that consumes the `TransactionInfo` instance and populates it using the provided `base_fee`.

**Comment by Gerson2102** [comment]
Hello. Can i take this?

**Comment by tcoratger** [comment]
> Hello. Can i take this?

Assigned

**Comment by Gerson2102** [comment]
@tcoratger hello sir. When this is included in the next release of reth, can you ping to work in this issue like the last time?

**Comment by Josh-121** [comment]
Pls assign, can complete within a day or less

**Comment by tcoratger** [comment]
> Pls assign, can complete within a day or less

Assigned
