### ISSUE TITLE
bug: eth transaction failure on testnet (pimlico)

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1073]
# Bug Report

**Kakarot RPC version:**

**Current behavior:**
Sending a transaction to the testnet with the below command fails to end and the transaction seems to revert on Starknet.
```
cast send 0x027b465F1Cfc3B2A70611587d3eE06362AA14E3a 0x1fad948c0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000433704c40f80cbff02e86fd36bc8bac5e31eb0c1000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000007152e0855bab82b8e10b8692e584ad034bd229120000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001e000000000000000000000000000000000000000000000000000000000000557300000000000000000000000000000000000000000000000000000000000086470000000000000000000000000000000000000000000000000000000000003d090000000000000000000000000000000000000000000000000000000003b9aca000000000000000000000000000000000000000000000000000000000008f0d180000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000058a3f44ef06ecccf45cfcf38920cb9e0fd23a66e315fbfb9cf0000000000000000000000004b4888942bfe98731727d0955cdd42cbecf3dd1900000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041fbfa9aa0bb3f120dee040df4bd44db5e4d952d58256dd62cd1bb3496e053a33026b6f80e7c3f354283111f1949932ef6a768e4dc034a7e38fe69d59929954e361c00000000000000000000000000000000000000000000000000000000000000 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --gas-limit 1000000
```

You can find the contract at `0x027b465F1Cfc3B2A70611587d3eE06362AA14E3a` [here](https://sepolia.kakarotscan.org/address/0x027b465F1Cfc3B2A70611587d3eE06362AA14E3a). 
Also seems like [this contract](https://sepolia.kakarotscan.org/address/0xcf3ccE0F2b6C0820Cbb33b22fd7A1D303bd8Ef3E) is responsible for funding the previous contract. We need more information in order to understand the exact flow of execution and be able to reproduce in Anvil/Kakarot local stack.

**Expected behavior:**

```[tasklist]
### Tasks
- [ ] Transaction should pass (Greg to check)
- [ ] Transaction resend mechanism should kick in and finish after about 1 minute (Thomas to check)
```

**Steps to reproduce:**
Run the above command. Check the logs in loki in order to find the Starknet hash and Ethereum hash. Can also filter on `send_raw` in order to verify that the transaction doesn't get resend.

**Comment by mouseless-eth** [comment]
Thanks for looking into this :)

I have made a [repo here](https://github.com/mouseless-eth/kakarot-aa-example) to deploy all contracts against a local anvil node. Running the `cast send` locally succeeds, however, running the same `cast send` through the kakarot RPC fails. 

### Some more context  on the transaction: 

The bundler would normally make a `handleOps` call to the EntryPoint contract to mine a UserOperation, in this case, we are making a raw `handleOps` using a very simple UserOperation.

### Related contracts on Kakarot-Sepolia

- Deterministic Deployer (Non EIP-155): `0xac19aa389d94E8b74dD25bd25C9F1DE96e812402` ([source code](https://github.com/Arachnid/deterministic-deployment-proxy))

- EntryPoint V0.6: `0x027b465F1Cfc3B2A70611587d3eE06362AA14E3a` ([source code](https://github.com/eth-infinitism/account-abstraction/blob/releases/v0.6/contracts/core/EntryPoint.sol))

- SimpleAccountFactory V0.6: `0xA3f44eF06ECccf45CfcF38920cB9e0FD23A66E31` ([source code](https://github.com/eth-infinitism/account-abstraction/blob/releases/v0.6/contracts/samples/SimpleAccountFactory.sol))

**Comment by greged93** [comment]
Thank you for this! Will get into it tmr with @tcoratger!

**Comment by mouseless-eth** [comment]
forgot to mention, but the original calldata in the cast command is slightly malformed causing it to revert during validation, the correct one is in the shared repo (also experiencing same behavior with the correct calldata). Sorry for the confusion :c

**Comment by greged93** [comment]
Just updating the issue with the current findings:
- Running the deployment on Anvil works fine.
- Running the deployment on Kakarot local devnet works fine (although with an issue to be fixed on the fee estimation during deployment of the Entrypoint v0.6 contract).
Transaction resources can be found here `Steps: 7846531 | Bitwise: 838 | Keccak: 58 | L1 Gas: 60151 | Pedersen: 462 | Range Checks: 364711`
- Running the deployment on Kakarot testnet fails on the last step of calling `cast send ...`. The error can be seen below:
```python
Error in the called contract (0x011c5faab8a76b3caff6e243b8d13059a7fb723a0ca12bbaadde95fb9e501bda):\n/Users/greg/code/cairo/kakarot/src/utils/utils.cairo:560:9: Error at pc=0:2135:
            assert res < ids.bound, f'split_int(): Limb {res} is out of range.'
        ^*******************^\nCould not reach the end of the program. RunResources has no remaining steps.\nCairo traceback (most recent call last):\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:295:16
        return load_aligned_words(
...
               ^*****************^\n/Users/greg/code/cairo/kakarot/src/kakarot/memory.cairo:294:9
        Helpers.split_word_128(value, element);
        ^************************************^\n
```

**Comment by greged93** [comment]
This can be closed as the Pimlico team was able to deploy.
