### ISSUE TITLE
test: add coverage for all edge cases of the `TracerBuilder`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1082]
**Describe the enhancement request**
We are missing quite a lot of coverage on the `TracerBuilder`. Add coverage on all failure cases. This will involve implementing a mocked `EthereumProvider` which can be added to the `test_utils` folder. Then check all failure paths of the `TracerBuilder` and cover them all in tests. Tests can be written in the file `builder.rs` itself.

**Comment by Gerson2102** [comment]
Please assign this to me @greged93

**Comment by tcoratger** [comment]
> Please assign this to me @greged93

assigned

**Comment by greged93** [comment]
hey @Gerson2102 just a note: you might need to use the `mockall` crate in order to mock the `EthereumProvider`. If you end up with problems along the way dont' hesitate to ask questions on the kakarot telegram channel, will answer as fast as possible

**Comment by Gerson2102** [comment]
@greged93 got it!

**Comment by Gerson2102** [comment]
I'm gonna need some guidance tbh @greged93 haha, I'm gonna post my questions here if is not a problem in some hours maybe.

**Comment by Gerson2102** [comment]
Ok now that i was seeing the code in more detail. My task here, is to create tests inside of `builder.rs` when those functions failed. Tests that are aiming to make errors in those functions to see if we are getting the correct values, in this case the errors through some of the enums that you guys are using in the code for errors right?

Am I understanding this well?

**Comment by greged93** [comment]
Yes this is correct @Gerson2102, the idea is to test the "bad path" and verify that we indeed error out if wrong values are provided.

**Comment by greged93** [comment]
hey @Gerson2102 what's the status on this? If this is too complicated @tcoratger or I can take over

**Comment by Gerson2102** [comment]
Hello @greged93. Sorry for not having this complete. I've been busy participating in StarkHack, if you guys need this task quick, go ahead and do it. If not, today i will spend time trying to solve it.

**Comment by greged93** [comment]
it's not urgent, just checking that you will have time to get to it

**Comment by greged93** [comment]
hey @Gerson2102 any update on this?

**Comment by Gerson2102** [comment]
> hey @Gerson2102 any update on this?

Hello @greged93. Right now I'm working on it, but I'm getting a bunch of errors. I have spend too much time assigned in this issue and its not solved, sorry for that. I think is better if you or @tcoratger does this. But please, I would like that you guys ping me in this issue when its done, i wanna see the solution.
