### ISSUE TITLE
feat: add user feedback for run out of resources txs

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1111]
# Feature Request

## Describe the Feature Request

At present, some transactions that run out of resources on the Starknet side are dropped by the Starknet sequencer without any feedback to the user. This leads to several issues:

- **Lack of Feedback:** Users receive no feedback about their transactions, leaving them unaware that their transaction failed.
- **Metamask Issues:** Users must reset their Metamask by clearing the cache to continue using Kakarot. This is because, despite the transaction failure, the nonce is incremented by 1.
- **Retry Service Overload:** The retry service, not seeing the transaction arrive in the finalized pool, attempts to retry it up to the retry limit. This generates even more load and complications on the sequencer side.

Ideally, our indexing service should be able to access transactions with this type of error. This would allow us to:
- Provide feedback to users about the status of their transactions.
- Remove these failed transactions from the retry pool to avoid unnecessary retries and reduce sequencer overload.

**Comment by tcoratger** [comment]
Should be closed by #1145 but we keep it open until this change is pushed into production to ensure this works as expected.

**Comment by greged93** [comment]
I think this works on prod no?

**Comment by tcoratger** [comment]
> I think this works on prod no?

Was part of the release of last week yes

**Comment by greged93** [comment]
closing since it reached production
