### ISSUE TITLE
dev: add more information for eth provider errors

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1112]
## Describe the Enhancement Request

In our ETH provider error file, we currently lack detailed information within error messages. Enhancing these messages with more precise information would be beneficial. 

### Current Issue
In the `eth_provider/error.rs` file:

[ETH Provider Error File](https://github.com/kkrt-labs/kakarot-rpc/blob/main/src/eth_provider/error.rs)

The error messages are not as informative as they could be. For example:

```rust
/// Error that can occur when interacting with the ETH API.
#[derive(Error)]
pub enum EthApiError {
    /// When a block is not found
    #[error("unknown block: {0}")]
    UnknownBlock(u64),
    //...
}
```

### Proposed Enhancement
We should enhance the error messages with more precise information. When necessary, we can use pre-built types to handle patterns such as `got/expected`. 

For instance, consider using the following type from the `reth` repository:

[Pre-built Error Type](https://github.com/paradigmxyz/reth/blob/df7c9ee3101f89b4ed10f2f78686bb16bf31d6f3/crates/primitives/src/error.rs#L8)

This can help in managing the `got/expected` pattern more effectively.

By improving error messages, we can provide better feedback and debugging information, making it easier to identify and resolve issues.

**Comment by edisontim** [comment]
Gm, can I do this ?

**Comment by tcoratger** [comment]
> Gm, can I do this ?

assigned
