### ISSUE TITLE
bug: Not view ETH balance but yes transactions

### ISSUE THREAD

**Issue by Nadai2010** [kkrt-labs/kakarot-rpc#1116]
# Bug Report

The balance ETH faucet does not appear after making the claim, it was with the Chrome browser and Metamask.

You can look at my account and see how I have created an erc-20 and it has been minted, but my ETH balance is 0.

[Account](https://sepolia-explorer.kakarot.org/accounts/0x62c77d44b06d321c412f8d8f1046b647c06bdd75)
[SC erc20 NAI](https://sepolia-explorer.kakarot.org/tokens/0x7885543d48b94a206500b23f6b362cf91fc812a5)

![imagen](https://github.com/kkrt-labs/kakarot-rpc/assets/112663528/66c1b7bc-c42e-42e0-9cea-f51fded13264)

Also in my MM both tokens come out to 0, it is the same account and rpc that I used to deploy.

![imagen](https://github.com/kkrt-labs/kakarot-rpc/assets/112663528/1bec33a6-4e88-4380-9d30-e0f17ffcf275)

**Steps to reproduce:**

1. Add the automatic RPC from the button and manually checked with the [doc](https://docs.kakarot.org/quick-start/#as-a-user-how-can-i-interact-with-kakarot-zkevm)
2. Add code access and address de ETH.
3. Overcome the captcha (pop op 0.05ETH received)
4. Create SC simple Wizard OZ and deploy and REMIX.
5. Mint NAI in Remix (Explorer Good with NAI total supply, mint...)

**Comment by greged93** [comment]
thanks for your issue @Nadai2010, we are looking into it

**Comment by greged93** [comment]
@Nadai2010 after investigation, we were out of Eth on the Faucet account! We funded it again and raised an issue for this
