### ISSUE TITLE
test: add testing to `isKakarotTransaction`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1117]
**Describe the enhancement request**

Test all branching conditions from the `isKakarotTransaction` function in typescript. Tests should be clear and cover all possible branching.

Tests should be placed in the `filter.test.ts` file.

**Comment by stevencartavia** [comment]
Hi, I would like to try this!

**Comment by stevencartavia** [comment]
Hi, I would like to try this!

**Comment by greged93** [comment]
assigned!
