### ISSUE TITLE
dev: improve `to_logs_filter`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1119]
**Describe the enhancement request**
Use `IntoIterator` on `FilterSet` once this [PR](https://github.com/alloy-rs/alloy/pull/784) is merged into Reth. Should be on the next release of Reth.

**Comment by Gerson2102** [comment]
Hey can you assign me this?

**Comment by Josh-121** [comment]
Can do great on this, pls assign. Can complete within a day or less
