### ISSUE TITLE
feat: pack calldata sent to Kakarot

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/kakarot-rpc#1153]
# Feature Request

Calldata is currently sent with 1 byte per felt. Considering a maximum of 30k felts in calldata, and 58k steps to unpack 30k bytes of packed calldata:

Option 1: no-packing: 30k * 0.128gas/felt = 3840 gas for max calldata
Option 2: 31-bytes calldata packing: (967 * 0.128gas/felt) + (0.0025gas/steps * 471k steps) = 1 301 gas for max calldata

Option 2 (with packing) is 3x cheaper, and solves the problem of calldata limit on the starknet chain.

Thus, implement calldata packing when sending a transaction to Kakarot. The calldata will be packed in 31 bytes chunks, and will be decoded by Kakarot accordingly.

**Comment by greged93** [comment]
Did we also bench how much extra steps we will incur with the decoding?

**Comment by enitrat** [comment]
yes, 
> 58k steps to unpack 30k bytes of packed calldata:

**Comment by greged93** [comment]
ahhhhhh sorry missed that! that's nice

**Comment by enitrat** [comment]
sorry that was for 4k bytes of calldata, let me update the metrics 😓

**Comment by tcoratger** [comment]
@enitrat @greged93 Solved by https://github.com/kkrt-labs/kakarot-rpc/pull/1174 correct?

**Comment by greged93** [comment]
calldata is now being packed by the RPC and unpacked by the indexer.
