### ISSUE TITLE
feat: fix dependabot to PR on Kakarot release

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1156]
## Description

As part of our upgrade flow, we need to automatically create a pull request to update the Kakarot submodules whenever there is a new release on the [Kakarot repository](https://github.com/kkrt-labs/kakarot).

### Preferred Solution

To achieve this, we can leverage Dependabot to check for updates in the Kakarot repository and create a pull request when a new release is detected. This involves configuring Dependabot to monitor the submodules and trigger updates accordingly.

### Steps to Implement

- **Update the `dependabot.yml` Configuration**:
   Modify the existing `dependabot.yml` file to include the necessary configuration for monitoring new releases in the Kakarot repository.

### Expected Outcome

With the updated `dependabot.yml` configuration, Dependabot will:

- Monitor the Kakarot repository for new releases.
- Create a pull request to update the Kakarot submodules in RPC repository when a new release is detected.

**Comment by ClementWalter** [comment]
closing since #1185 and https://github.com/kkrt-labs/kakarot/pull/1200
