### ISSUE TITLE
dev: move `TRANSACTION_MAX_RETRIES` to env

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1162]
**Describe the enhancement request**
Currently, we assign a fixed value to `TRANSACTION_MAX_RETRIES` of 10. It could be interesting to have this as an env variable which can be customised based on the demand on the network. Thus, modify `TRANSACTION_MAX_RETRIES` to load it from the env.

Don't forget to update the `.env.example`, as well as the various Docker Compose and Dockerfiles!

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by jbmkahdeksan** [comment]
Hi, I want to take this issue, please
!
