### ISSUE TITLE
bug: Issue while fetching data with address(0) in the argument (runresource error)

### ISSUE THREAD

**Issue by vanshtah** [kkrt-labs/kakarot-rpc#1163]
# Bug Report

**Kakarot RPC version:**

**Current behavior:** When passing the address(0) on the argument we receive an error related to runresource, without the address(0) the function returns the right data

**Expected behavior:** It should return data correctly with address(0), (we have checked the result on other EVMs)

**Steps to reproduce:** 

Contract Address: 0x4855443432F58b968b49b3732205866E23c97d4c
Json Artifact/ABI : [VaultReader.json](https://github.com/user-attachments/files/15685750/VaultReader.json)
Function to be called: getVaultTokenInfoV4

Arguments to pass: 

- 0x22eFEB944d65D982cA871Ff702a2eA8a0BCFBafC
- 0xEd65BD1882CccCf391d9548E2F5d772cCD2cc187
- 0xf42991f02c07ab66cfea282e7e482382aeb85461
- 1000000000000000000
- ["0x0000000000000000000000000000000000000000","0xf42991f02c07ab66cfea282e7e482382aeb85461","0x9ee1aa18f3feb435f811d6ae2f71b7d2a4adce0b","0x057e8e2bc40ecff87e6f9b28750d5e7ac004eab9","0xad45924555be89f07019376eeb4cb30e3d857cfd","0xb0aaaa41170ad29b00fc166e41da3100d11edf68"]

**Related code:** The function which we deployed

```

    function getVaultTokenInfoV4(address _vault, address _positionManager, address _weth, uint256 _usdgAmount, address[] memory _tokens) public view returns (uint256[] memory) {
        uint256 propsLength = 15;

        IVault vault = IVault(_vault);
        IVaultPriceFeed priceFeed = IVaultPriceFeed(vault.priceFeed());
        IBasePositionManager positionManager = IBasePositionManager(_positionManager);

        uint256[] memory amounts = new uint256[](_tokens.length * propsLength);
        for (uint256 i = 0; i < _tokens.length; i++) {
            address token = _tokens[i];
            if (token == address(0)) {
                token = _weth;
            }

            amounts[i * propsLength] = vault.poolAmounts(token);
            amounts[i * propsLength + 1] = vault.reservedAmounts(token);
            amounts[i * propsLength + 2] = vault.usdgAmounts(token);
            amounts[i * propsLength + 3] = vault.getRedemptionAmount(token, _usdgAmount);
            amounts[i * propsLength + 4] = vault.tokenWeights(token);
            amounts[i * propsLength + 5] = vault.bufferAmounts(token);
            amounts[i * propsLength + 6] = vault.maxUsdgAmounts(token);
            amounts[i * propsLength + 7] = vault.globalShortSizes(token);
            amounts[i * propsLength + 8] = positionManager.maxGlobalShortSizes(token);
            amounts[i * propsLength + 9] = positionManager.maxGlobalLongSizes(token);
            amounts[i * propsLength + 10] = vault.getMinPrice(token);
            amounts[i * propsLength + 11] = vault.getMaxPrice(token);
            amounts[i * propsLength + 12] = vault.guaranteedUsd(token);
            amounts[i * propsLength + 13] = priceFeed.getPrimaryPrice(token, false);
            amounts[i * propsLength + 14] = priceFeed.getPrimaryPrice(token, true);
        }

        return amounts;
    }
```

**Other information:** 
[VaultReader.json](https://github.com/user-attachments/files/15685750/VaultReader.json)

**Comment by greged93** [comment]
hey @vanshtah, can you verify the vault address? Calling `cast code` on it returns an empty value and I don't see anything deployed on the explorer at this address. Also I am seeing that you are using the wrong WETH address, it should be `0x761612F0C8bdf8cF10e6F10045E2Ca7cbffBa8A3`.
