### ISSUE TITLE
bug: different in events when replaying Kakarot Sepolia transactions on Madara

### ISSUE THREAD

**Issue by apoorvsadana** [kkrt-labs/kakarot-rpc#1177]
We were replaying all txs that were executed on Kakarot Sepolia on Madara to check if it works as expected. For each transaction executed we 

1. Match all events in the tx receipt
2. Ignore the fee transfer event only (as the sequencer address and amount differs between Madara and Kakarot)

On transaction `0x41ed84a54d0f464bdf91282f2cdffc929ddcd082ae82822484a916b19d088e1` (SN hash), we found a bug that the events were not matching. The exact difference can be found here - https://www.diffchecker.com/8rDHGtNM/. If we ignore the fee transfer event, the mismatch is with a specific element in event data being `0x8` on Madara but `0x6` on Kakarot.

We aren't very sure on how to debug this at the moment and need some help in understanding the exact contract call and event data which was fired in this txn to reason why there might have been a difference.

**Comment by greged93** [comment]
closing this as currently not able to debug it
