### ISSUE TITLE
feat: create a new `make` command to check linting

### ISSUE THREAD

**Issue by jbmkahdeksan** [kkrt-labs/kakarot-rpc#1183]
# create a new `make` command to check linting

I realized that using clippy locally is not enough to detect the linting demands of Kakarot's projects. Several flags and other commands are used to enforce this:

`cargo check && cargo fmt --all -- --check && cargo clippy --workspace --all-features --all-targets -- -D warnings`

I realized this by a comment of @tcoratger on a previous PR, when the pipeline of GitHub actions failed. 

So I am proposing to create a new `make` command to encapsulate this behavior and better check the linting before submitting changes. 
This will avoid unnecessary re-runs of GitHub jobs and also will make an smoother developing process.

**Solution**
Create a new `make` in the makefile.
(Haven't checked, but this could be also useful for the other Kakarot Labs repos)

**Comment by aniketpr01** [comment]
@jbmkahdeksan can i take this?
Query: should the new make command be the one mentioned?

**Comment by tcoratger** [comment]
Hey @jbmkahdeksan 

Thanks for opening this. Unfortunately, I don't think it's a good idea to do a dedicated make command. Indeed, the instructions mentioned in this command are very generic and are part of most Rust repositories.


To be able to have a better view of possible clippy or fmt errors, I invite you to install the rust analyzer on your working environment. For example if you use vs code you can have these parameters in your configuration

```
 "[rust]": {
 "editor.defaultFormatter": "rust-lang.rust-analyzer",
 "editor.formatOnSave": true
 },
```

which will allow you to have automatic formatting when you save your file. In addition, the rust analyzer normally detects errors/clippy on its own and points them out to you to help you correct them.

Don't hesitate to come back to us if you have any problems with your configuration.
