### ISSUE TITLE
feat: add debug_traceCall

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1193]
# debug_traceCall

## Metadatax

- name: traceCall
- prefix: debug
- [specification](https://www.quicknode.com/docs/ethereum/debug_traceCall)

## Specification Description

Returns the number of possible tracing result by executing an eth call within the context of the given block execution.

### Parameters

See [Reth implementation](https://github.com/paradigmxyz/reth/blob/f218774950bf1562cbf60e20b162a70267c937d1/crates/rpc/rpc-api/src/debug.rs#L105).

### Returns

See [Reth implementation](https://github.com/paradigmxyz/reth/blob/f218774950bf1562cbf60e20b162a70267c937d1/crates/rpc/rpc-api/src/debug.rs#L105).

## Kakarot Logic

Study the way Reth does it but this probably needs to be implemented in the `tracing` folder, using the `revm::Evm` instance.

**Comment by tcoratger** [comment]
Blocked until https://github.com/paradigmxyz/reth/pull/8860 is included in the next release of reth and we need to bump.
