### ISSUE TITLE
dev: add constant file to the indexer

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1196]
**Describe the enhancement request**

At the moment, we have constants like `KAKAROT_ADDRESS` (or others) defined in different places or sometimes multiple times across the codebase. This can be seen in the following instances:

https://github.com/kkrt-labs/kakarot-rpc/blob/74d34ce846113b32baa71de91bc83aec59361a88/indexer/src/utils/filter.ts#L4

https://github.com/kkrt-labs/kakarot-rpc/blob/74d34ce846113b32baa71de91bc83aec59361a88/indexer/src/provider.ts#L8

It would be beneficial to have a dedicated file for constants where we can store all the constants needed for the indexer and access them from there. This will improve maintainability and ensure consistency across the codebase.

**Comment by stevencartavia** [comment]
Hi, can I take this?

**Comment by tcoratger** [comment]
> Hi, can I take this?

Assigned
