### ISSUE TITLE
dev: add errors `EvmError`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1204]
**Describe the enhancement request**
Check the [errors](https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/errors.cairo) that the Kakarot contract can emit and compare it with the file at `eth_provider/error.rs`. Some errors have been added that aren't currently implemented for us.

You should add the following errors:
- `unauthorizedPrecompile`
- `invalidCairoSelector`

Additionally, you should add the necessary conversion in `impl From<Vec<FieldElement>> for EvmError`. 

**Time**
This PR should take 1h.

**Comment by Gerson2102** [comment]
Hey @greged93 can i work on this?

**Comment by dznes** [comment]
Hello @greged93 i would like to do this task, if possible.

**Comment by greged93** [comment]
@Gerson2102 you commented on here first but I see you already have an issue so I will assign to @dznes
