### ISSUE TITLE
dev: improve latency of apibara indexing

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1210]
**Describe the enhancement request**

Note: needs further scoping by code owners, @tcoratger or @greged93 
Context: I understand that Apibara latency is ~3s due to an env variable for pending block indexing

**Describe Preferred Solution**

We should aim to make this as low as possible to improve UX.

**Comment by greged93** [comment]
this has already been changed here
https://github.com/kkrt-labs/kakarot-rpc/commit/e71a0b0328081649d3f47f391875dea4db9810c2
