### ISSUE TITLE
dev: replace `starknet_crypto::FieldElement` with starknet-types-core

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1233]
**Describe the enhancement request**

At the moment, we are using an old version of `starknet-rs` crypto crate. Following the merge of https://github.com/xJonathanLEI/starknet-rs/pull/562, we should migrate to the new version and replace our current `FieldElement` around the codebase with the new `Felt` type. 

This update involves replacing all instances of the `FieldElement` type in our codebase with the new `Felt` type introduced in the update.

## Benefits
- Improved performance and security with the latest version of the crypto crate.
- Staying up-to-date with the latest developments and fixes in the starknet-rs library.

**Comment by greged93** [comment]
This will probably lead us to need to bump Katana as well no? Are we blocked there or would that be possible?

**Comment by tcoratger** [comment]
> This will probably lead us to need to bump Katana as well no? Are we blocked there or would that be possible?

Yes that's true, just put a blocked tag to remind us that we need to update Katana as well and it's blocked at the moment due to fork issue.

**Comment by tcoratger** [comment]
blocked by #1245

**Comment by greged93** [comment]
I think you can start this whenever you want @eugypalu

**Comment by tcoratger** [comment]
> I think you can start this whenever you want @eugypalu

I think this is already work in progress as far as I understood with our week discussions

**Comment by eugypalu** [comment]
Current status of the issue:
- The issue is blocked because it is not possible to run the tests without upgrading this: https://github.com/kkrt-labs/blockifier
- It is possible to run the cargo build without errors, and all FieldElement have been migrated to Felt.

**Comment by tcoratger** [comment]
> Current status of the issue:
> 
> * The issue is blocked because it is not possible to run the tests without upgrading this: https://github.com/kkrt-labs/blockifier
> * It is possible to run the cargo build without errors, and all FieldElement have been migrated to Felt.

Can you push a draft pr so that we can check what happens with the update of blockifier?

**Comment by eugypalu** [comment]
> > Current status of the issue:
> > 
> > * The issue is blocked because it is not possible to run the tests without upgrading this: https://github.com/kkrt-labs/blockifier
> > * It is possible to run the cargo build without errors, and all FieldElement have been migrated to Felt.
> 
> Can you push a draft pr so that we can check what happens with the update of blockifier?

Sure, opened: https://github.com/kkrt-labs/kakarot-rpc/pull/1296
