### ISSUE TITLE
dev: add test coverage for `EthereumBlockStore`

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1247]
**Describe the enhancement request**

Similar to what was done here https://github.com/kkrt-labs/kakarot-rpc/pull/1243, it would be interesting to add a complete test coverage (covering all possible cases), for the `EthereumBlockStore`:

https://github.com/kkrt-labs/kakarot-rpc/blob/ec9902678e62e88f9c8c591e8cd3595056bcb57e/src/eth_provider/database/ethereum.rs#L123-L201

@hhamud you could be interested by this one?

**Comment by hhamud** [comment]
sure, just pinged you on telegram.
