### ISSUE TITLE
dev: add `poetry` as a requirement in the README.md

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1256]
**Describe the enhancement request**
The README doesn't mention the need to have `poetry` installed in order to run the `make setup` command. Add this requirement to the README and a link to the [poetry](https://python-poetry.org/docs/) installation steps.

Time: 30 minutes

**Comment by elielnfinic** [comment]
Can I take this?

**Comment by greged93** [comment]
Sure!
