### ISSUE TITLE
test: generate a `expectedTransformData.json`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1258]
**Describe the enhancement request**

Taking the `transactionsData.json`, pass it through the `transform` function in order to convert all the values and dump this into a json file. Then use this json file which will now contain the expected output data from the `transform` function for our input test data in order to test the output values in the tests `toTypedEthTx with real data` and `transform with real data`.

Time: 2 hours

**Comment by elielnfinic** [comment]
I can take this too

**Comment by greged93** [comment]
hey @elielnfinic, we only assign 1 issue per person, once you finish the other one I will assign this one.

**Comment by elielnfinic** [comment]
That sounds good.

**Comment by adrianvrj** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hi my name is Adrian, I am a software engineer currently looking forward to contribute in open source projects, I have experience with Rust and Cairo issues

### How I plan on tackling this issue
	1.	Obtain the transactionsData.json file.
	2.	Define or locate the transform function: This function will process the input data from transactionsData.json and generate the transformed output.
	3.	Generate expectedTransformData.json: Use the transform function to process the input data and save the transformed data to a new JSON file.
	4.	Use expectedTransformData.json in tests: Use this file to test the output of the toTypedEthTx function, ensuring that the real data transformation matches the expected output.

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hi, my name is Jose Mario. I am a developer with over 15 years of experience. I am currently eager to contribute to open-source projects and have been learning Rust, Cairo, and Solidity. My most recent role was as a senior backend developer, where I specialized in technologies such as Node.js, JavaScript, TypeScript, among many others.

### How I plan on tackling this issue
1 . Begin by reading the transactionsData.json file. This is done using a fs read operation in javascript (or an equivalent method in another language.
2. Apply transform function to the loaded data. This function convert or processes the data according to the required transformation logic.
3. After transforming the data, write the processed data to a new json file
4. Test the toTypedEthTx function using the transformed data to ensure it produces the correct results

**Comment by Utkarsh-626744** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I am a software engineer at Zscaler with a year of experience in providing cloud security solutions. My role involves developing secure, scalable cloud-based applications, which has honed my skills in cloud infrastructure, security protocols, and system architecture. Additionally, I have developed a blockchain project that connects multiple wallets, showcasing my proficiency in blockchain technology, smart contract development, and DApp deployment. This project is deployed on Netlify and available on my GitHub profile. My expertise in cloud security ensures that blockchain projects are secure from various threats while being scalable and efficient. I excel in integrating blockchain networks, deploying applications, and maintaining them using CI/CD pipelines. My collaborative approach, problem-solving skills, and customer-centric mindset further enhance my ability to deliver innovative and secure solutions in both cloud security and blockchain domains.

### How I plan on tackling this issue
We start with transactionsData.json, which contains the raw transaction data. This data will be processed through a transform function to convert the values into a desired format. The transform function will take the raw transaction data and process each transaction to convert its values. The details of the transformation logic depend on the specific requirements, but the goal is to ensure the values are formatted correctly for further processing. After processing the raw data through the transform function, the resulting data will be dumped into a new JSON file. This JSON file will now contain the expected output data from the transform function. With the transformed data stored in the new JSON file, we can now use this data for testing. Specifically, we will test the toTypedEthTx function and the transform function using this real, transformed data.

**Comment by Zeegaths** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I graduated frombasecamp 9, cairo masterclass and web3bridge. Im farmiliar with both cairo and evem

### How I plan on tackling this issue
create a state variable to store the json data generated from the function or call call the test inside the function

**Comment by mamicho16** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I've executed projects using files .json. I have knowlegde to work with this files.

### How I plan on tackling this issue
First of all I'll review the code to understand the functions and then proceed to do a solution when i'll be completely sure about th functionality.
