### ISSUE TITLE
feat: revert preconfs logic; only emit receipts when a block is mined

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1279]
# Feature Request

**Describe the Feature Request**

- it seems preconfs (ability to create receipts before block is mined) aren't supported anywhere (no SDK is prepared for it)
- it creates probable bugs with existing tools (indexers)
- went and talked to EPBS peeps and preconfs people, and it looks no one is building support for preconfs

**Describe Preferred Solution**

cc @greged93 need further scoping, but essentially, revert back to normal behaviour where receipts are emitted when the block is mined

**Comment by greged93** [comment]
do we still want this?

**Comment by Eikix** [comment]
i'm not sure; for now let's close it
