### ISSUE TITLE
feat: add the missing important "infrastructure contracts" on Kakarot

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1288]
# Feature Request

**Describe the Feature Request**

There is a new RIP for rollups which is to simplify adding a list of important contracts that are factories, e.g. arachnid and createX.

There are 4 contracts in the RIP, so I think we could add the missing two: https://github.com/ethereum/RIPs/pull/30/files#diff-8fb76c4cfd3e4dc31a49e0ecb56ea00561f0f2af4b4d4353c52b62e95fc6a8bbR39 

**Describe Preferred Solution**

- whitelist the pre eip-155 txs that deployed the contracts
- add all these contracts in our deployments scripts

Note cc @greged93 is arachnid and createX part of the deploy kakarot scripts?

**Comment by greged93** [comment]
@Eikix yes arachnid and createX are part of the deploy scripts

**Comment by Eikix** [comment]
Closing this issue in favor of https://github.com/kkrt-labs/kakarot/issues/1457
