### ISSUE TITLE
dev(indexer): verify event origin

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1290]
**Describe the enhancement request**

Currently, we do not verify that origin of an event (present in the `fromAddress` field of events) is equal to the `KakarotAddress`. We should verify this as it could pose an issue if we ever allow arbitrary calls to Cairo contracts from Kakarot.

**Details**

In the function `toEthLog`, update the logic in order to verify that the `fromAddress` of each event is the `KakarotAddress`. This can be added in the lines below:
https://github.com/kkrt-labs/kakarot-rpc/blob/3cee3db54ada8ee1622c625e51f1614c5feccb02/indexer/src/types/log.ts#L50-L53

There, you can verify that the `fromAddress` field of the event is equal to `KAKAROT_ADDRESS` which can be imported from:
https://github.com/kkrt-labs/kakarot-rpc/blob/3cee3db54ada8ee1622c625e51f1614c5feccb02/indexer/src/constants.ts#L48-L52

Time: 20 min

**Comment by swetshaw** [comment]
Can I take this up ?

**Comment by DilanHern** [comment]
Hello @greged93 , my name is Dilan. I´ve worked with rust a lot of times so i think I should be able to complete this issue approximately in a week. I would like to investigate more and try to solve it. ¿Could i take this issue? I´m a responsible person.

**Comment by greged93** [comment]
Hey sorry @DilanHern but I will assign this to Sweta as she commented first
