### ISSUE TITLE
bug: blocking call on Juno 

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1292]
# Bug Report

**Current behavior:**
Juno instance seems to suffer from a blocking call with locks the instance every once in a while. We have seen the instance getting locked for +10 min.

**Expected behavior:**
Call shouldn't lock the instance and should fail after a while.

**Steps to reproduce:**
TBD. Currently being evaluated with Anukkrit.

**Comment by mimiethetechsis** [comment]
@greged93 I'd like to work on this. Can I be assigned?

**Comment by greged93** [comment]
Hey @mimiethetechsis this isn't really opened for contribution as it involves debugging with our infra which you don't have access to

**Comment by mimiethetechsis** [comment]
Alright then

**Comment by greged93** [comment]
it was diagnosed that the instance wasn't locking but that it was just capped at max VM jobs because it constantly had heavy jobs in the queue.
