### ISSUE TITLE
Tracking: Hive/rpc-compat conformance

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-rpc#130]
# Goal/Aim

We aim to utilize tests described [here](https://github.com/ethereum/execution-apis/tree/main/tests) and eventually ran via [this runner](https://github.com/ethereum/hive/tree/master/simulators/ethereum/rpc-compat) to establish a claim of confirmity!  

This issue is meant to 
- discuss/assess the relevance of the conformance tests to our specific goal/stage of development.
  - i.e. are there some logic that these conformance tests touch that don't make sense for our use case?
- track progress in what logic is testable in our implementation that overlaps with the conformance tests

# Status

I went through the codebase and did a high level diff to the best of my understanding against the list of tests [here](https://github.com/ethereum/execution-apis/tree/main/tests). I made the effort to distinguish between rpc features that are tested with examples, that have examples, that are implemented with neither tests or examples, or that are implemented via a hardcoding of logic of some sort.

And, finally, the methods that are not implemented and have no issues.

I am leaving hardcoded implementations as undone just so we can rehash rationale or create refined issues.

I initially formatted this issue assuming that the [tasklists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists) feature was public across projects, but apparently an organization still has to request access. 

On the execution side, we need a way to initialize the kakarot state (as an implementation detail, the starknet devnet state) per a [genesis.json file](https://github.com/ethereum/execution-apis/blob/main/tests/genesis.json) and create blocks per a [chain.rlp file](https://github.com/ethereum/execution-apis/blob/main/tests/chain.rlp).

##  rpc methods that conformance tests utilize and their current state 
  - [ ] debug_getRawBlock
  - [ ] debug_getRawHeader
  - [ ] debug_getRawReceipts
  - [ ] debug_getRawTransaction
  - [X] eth_blockNumber
    - with example
  - [X] eth_call
    - with example
  - [X] eth_chainId
    - implemented without example or test
  - [ ] eth_createAccessList
    - marked todo in codebase. 
    - ? would not be applicable for the 0.10 version of kkrt
  - [x] eth_estimateGas
    - hardcoded
  - [X] eth_feeHistory
    - w/ example
  - [X] eth_getBalance
    - w/ example
  - [X] eth_getBlockByHash
    - implemented/tested
  - [X] eth_getBlockByNumber
    - implemented/tested
  - [X] eth_getBlockTransactionCountByHash
    - implemented/tested
  - [X] eth_getBlockTransactionCountByNumber
    - implemented/tested
  - [X] eth_getCode
    - w/ example
  - [ ] eth_getProof
    - marked todo in codebase
  - [x] eth_getStorage
    - #65 
  - [X] eth_getTransactionByBlockHashAndIndex
    - implemented with test
  - [X] eth_getTransactionByBlockNumberAndIndex
    - implemented w/ test
  - [x] eth_getTransactionByHash
    - hardcoded with a default ether transaction
  - [x] eth_getTransactionCount
    - hardcoded with a value of 3
    - #101 
  - [X] eth_getTransactionReceipt
    - w/ example
  - [x] eth_sendRawTransaction
    - marked todo in codebase
  - [X] eth_syncing

**Comment by Eikix** [comment]
Reopening issue as dev effort is rekindled

**Comment by jobez** [comment]
did an exploration and used reth's utils to parse the [chain.rlp file](https://github.com/ethereum/execution-apis/blob/main/tests/chain.rlp) https://gist.github.com/jobez/fbdc9c5c912d1e3906fe004f464d021a

i know @danilowhk  is looking into the devops pov

### high level flow would be

- initialize whatever is serving as the test starknet rpc piece with blocks that are converted from the chain.rlp x genesis.json
- initialize kkrt rpc
- run equiv process to [this runner](https://github.com/ethereum/hive/tree/master/simulators/ethereum/rpc-compat)

**Comment by greged93** [comment]
hive testing has been added to the CI, as such closing this.
