### ISSUE TITLE
dev: balance validation in `send_raw_transaction`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1303]
**Describe the enhancement request**
Add a check of the balance of the sender in the `send_raw_transaction` in order to avoid sending the transaction if the user doesn't have enough balance.

This can be added in the `validate_transaction` function, which should query the ETH balance of the user and check that the total cost for the transaction can be covered with the current balance.

The simple approach would just be to query the balance of the user each time a transaction is received. However, this would mean we will emit a lot of queries to the Juno instance since each retry will also trigger a call.

Need to design a smart solution which avoids a requery of the balance for each retry.

**Comment by eugypalu** [comment]
### Proposed Design
#### Workflow:
1. **Initial Balance Query**: When a transaction is first received, query the sender's balance.
2. **Store Balance and Reusability Flag**:
   - Store the queried balance.
   - Store a boolean flag indicating whether the balance can be reused for future transactions (initially set to `true`).
3. **Balance Validation**:
   - If the balance is sufficient and the transaction is valid, set the reusability flag to `false`.
   - If the transaction is not valid, keep the reusability flag `true` to avoid re-querying the balance.

#### Storage Solution:
- **Storage Solution**: 
   - **Cache (Redis)**: Using a caching solution like Redis would be optimal for quick access and performance. However, setting up a dedicated cache for this single purpose might not be justified in terms of complexity and resource management.
   - **Database (MongoDB)**: As an alternative, MongoDB can be used to store the balance and reusability flag in a key-value structure. This approach integrates well with our existing setup and simplifies the overall architecture.

- **Document Structure**:
  ```json
  {
    "key": "user-address",
    "value": {
      "balance": "user-balance",
      "reusable": true/false
    }
  }
  ```

**Comment by Eikix** [comment]
Closing in favour of #1321
