### ISSUE TITLE
dev: move tests in separate `*_test.rs` files

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#1313]
**Describe the enhancement request**

Tests are usually just put at the end of a given file in the `mod test` like

```
#[cfg(test)]
mod tests {
    //
```

While this is fine for small files, it's also a common practice to put them in a separate file when the source becomes bigger, like

```
|--
  |-  utils.rs
  |-  utils_test.rs
```

with 

```
#[cfg(test)]
#[path = "utils_test.rs"]
mod test;
```

in the `utils.rs`.

The purpose of this issue is to refactor the tests of the crates to adopt the split files pattern.

**Comment by Gerson2102** [comment]
Hello @ClementWalter. While reading this issue, seems easy. I have contributed before to this project. Lmk if I can do this refactor.

**Comment by greged93** [comment]
I don't know if we want this, let us talk @ClementWalter, this isn't standard in rust

**Comment by greged93** [comment]
@ClementWalter I think I will close this, after checking some repos this really isn't idiomatic in Rust. I think if you start to pile up too much tests, it probably means that you have pilled up too much code in the file and should instead split the file along with the tests, iso just splitting the tests.
