### ISSUE TITLE
feat: integrate our mempool with the account manager service

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1351]
# Feature Request

Now that https://github.com/kkrt-labs/kakarot-rpc/pull/1321 is merged, the mempool that is filled inside the `send_raw_transaction` should also be integrated properly by our account manager service for it to take and remove transactions from the mempool properly

https://github.com/kkrt-labs/kakarot-rpc/blob/f97902f15b488f4fb9db51738e23f287154033f4/src/pool/mempool.rs#L61

**Comment by greged93** [comment]
done, fixing the tests right now
