### ISSUE TITLE
dev: replace dojo `SequencerConfig`

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1397]
To setup the Katana sequencer, we are using a `SequencerConfig` structure:

https://github.com/kkrt-labs/kakarot-rpc/blob/4061385ee263d5ac514b92464853deb7cc471539/src/test_utils/katana/mod.rs#L72

But this structure is in the process of removal on Dojo side:

https://github.com/dojoengine/dojo/blob/60c1575927db63e98ababda56c5ffa9f6337fb56/crates/katana/core/src/sequencer.rs

so that we need to replace it in the codebase to avoid relying on something deprecated.

Related https://github.com/kkrt-labs/kakarot-rpc/pull/1389#discussion_r1771564191

**Comment by varun-doshi** [comment]
I can take this up
Any pointers would be helpful as well

**Comment by tcoratger** [comment]
@varun-doshi I think that you should wait for https://github.com/dojoengine/dojo/issues/2467 because for now we still need to use this struct as long as it is used to initialize our testing sequencer using this:

https://github.com/dojoengine/dojo/blob/60c1575927db63e98ababda56c5ffa9f6337fb56/crates/dojo-test-utils/src/sequencer.rs#L38

**Comment by varun-doshi** [comment]
Understood...I'll wait for it go through and then get started here
Are we expecting Dojo to introduce `SequencerConfig` in some other way? Or would we be needing to recreate the functionality of `SequencerConfig` by ourselves in this codebase?

**Comment by greged93** [comment]
hey @varun-doshi, just letting you know that https://github.com/dojoengine/dojo/issues/2467 was merged.
