### ISSUE TITLE
dev: simplify `WithOtherFields<T>` usage

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#1398]
In our codebase, we use the `other` field of transactions to store `isRunOutOfResources` information. This leads to extensive usage of `WithOtherFields<T>` throughout the code after the merge of https://github.com/kkrt-labs/kakarot-rpc/pull/1389, especially when handling conversions between RPC and primitive types, as seen in https://github.com/paradigmxyz/reth/blob/fba837468cac5143b415c9dd4fdc9218d71a926b/crates/primitives/src/alloy_compat.rs#L55-L212.

However, this approach is complex and can be optimized for better readability and management.

### Proposal

1. Simplify where possible: identify and remove unnecessary uses of `WithOtherFields<T>`, replacing them with just `T` where the extra fields aren't needed.
2. Define a reusable type: introduce a type alias such as `ExtendedTransaction = WithOtherFields<Transaction>` (and similar for blocks) to standardize its usage where necessary.

**Comment by Samrath49** [comment]
Hi @tcoratger, I would like to contribute to this issue, kindly assign me.

**Comment by tcoratger** [comment]
@Samrath49 Assigned

**Comment by maxslimb** [comment]
@tcoratger can you explain more about the issue with references to simplifying WithOtherFields<T> usages?

**Comment by sajalbnl** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I want to work on this

**Comment by udyan13** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
As a seasoned Rust developer, I have a proven track record of optimizing complex codebases for both performance and readability. My experience includes refactoring legacy code, implementing type aliases, and working with RPC systems. I'm confident in my ability to improve the clarity and maintainability of our WithOtherFields<T> code while ensuring functionality remains intact. I'm a collaborative problem-solver who is committed to producing high-quality code.

### How I plan on tackling this issue

The summary you provided is clear and well-structured. Here are a few points to consider for improvement and clarity:

Strengths
Clarity: The steps are articulated in a logical order, making it easy to follow your approach.
Comprehensive: It covers all essential aspects, from analysis to documentation and communication.
Focus on Collaboration: Emphasizing team communication is a great addition, as it highlights a collaborative mindset.
Minor Suggestions
Conciseness: While the paragraph is clear, you might condense some phrases to enhance readability.
Terminology Consistency: Ensure terms like "redundant" and "essential" are clearly defined if the audience may not be familiar with them.
Revised Version
Here’s a slightly refined version:

To approach the problem, I would start with a thorough code review to identify all instances of WithOtherFields<T> and assess their necessity. These usages would be categorized into three groups: essential cases required for functionality, redundant cases that can be safely removed, and ambiguous cases needing further team discussion. For the redundant cases, I would develop a plan to replace WithOtherFields<T> with T, documenting the rationale for retaining it in essential cases. Additionally, I would introduce type aliases, such as ExtendedTransaction and ExtendedBlock, to standardize usage. Ensuring comprehensive testing is crucial; I would run existing tests and add new ones following the changes. I would also update relevant documentation to reflect these modifications and provide guidelines for future usage. Throughout the process, maintaining open communication with the team would be essential for gathering feedback and ensuring alignment. This structured approach aims to reduce complexity while preserving functionality and enhancing code readability.

**Comment by PabloVillaplana** [comment]
Hey Tomas @tcoratger  Can I take this one?  ☝️

**Comment by MooreTheAnalyst** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot).

### My background and how it can be leveraged
hi

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot).

### My background and how it can be leveraged
I am a core linux dev, i have worked on ci/cd pipelines before, alongside that i have worked on ML models, i am on an outlook to learn more in more fields, i think ill be able to tackle this issue

### How I plan on tackling this issue
a) Audit current usage of WithOtherFields<T>
b) Createe type aliases (ExtendedTransaction, etc.)
c) Refactor code to use new types where appropriate
d) Update conversion functions between RPC and primitive types
e) Thoroughly test changes
f) Update documentation

**Comment by Gerson2102** [comment]
Hey @tcoratger. So where should I look for all the usages of the `WithOtherFields<T>` inside of the code? Maybe all those files that u changed on the linked PR of the issue description?
