### ISSUE TITLE
dev: improve modulo for chain

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1408]
**Describe the enhancement request**

Clean up the code for the chain id modulo taken a few times across the code base (search for "1 << 53" to find them all).
https://github.com/kkrt-labs/kakarot-rpc/pull/1381#discussion_r1778210901

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hello

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Please can I be assigned this issue? This would be my first time contributing to this ecosystem and I’d love to be given the opportunity. I am a blockchain Developer, and my experience includes html, css, react, JavaScript,TypeScript and solidity, python and Cairo.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hi , i am a blockchain developer , with experience in languages like , javascript, cario, typescript ,html,css, etc . This would be my first time contributing to this ecosystem and i am exicted about it ,please i will like to work on this issue . i am ready to work.

### How I plan on tackling this issue
To approach this issue, i will  begin by searching the codebase for instances where "1 << 53" is used, as this represents the chain ID modulo being applied multiple times. 
 Then refactor the code to centralize this logic into a single, reusable function or utility, which can be called wherever the chain ID modulo operation is needed. This will improve code maintainability and reduce duplication. After refactoring,  i will then ensure to update all instances across the codebase to use the new centralized function, and thoroughly test to confirm the logic behaves as expected.

**Comment by varun-doshi** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
I've previously contributed to Shinigami and Btczee...both Starknet projects.
I'm a Rust developer by profession

**Comment by sfroment** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/kakarot-zkevm).

### My background and how it can be leveraged
Hey :wave:
Software eng for some years

### How I plan on tackling this issue
extract the 1 << 53
use a const
make a func 
use the func where needed

**Comment by raizo07** [comment]
@greged93 acknowledged.

**Comment by greged93** [comment]
@raizo07 any update on this?

**Comment by raizo07** [comment]
Yes, sending soon.

**Comment by greged93** [comment]
closed by #1435
