### ISSUE TITLE
dev: pool configuration [0.5]

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1409]
**Describe the enhancement request**

The pool configuration currently used for the `#[cfg(not(feature = "hive"))]` will cause the pool to use a default minimal base fee of 0. This might cause a conflict with the base fee used in the execution layer, meaning the best would be to retrieve the base fee value at start up from the Kakarot contract and use this as the minimal base fee.

**Pseudocode of the request**
```rust
let contract = KakarotReader::new(...);
let base_fee = contract.get_base_fee().block_id(Latest).call().await;
...
let pool_config = PoolConfig{base_fee: base_fee,...};
```

Duration: 0.5 hour

**Comment by ooochoche** [comment]
@greged93 can i work on this

**Comment by greged93** [comment]
hey @ooochoche, this is a little involved so we will have to do it ourselves.

**Comment by ooochoche** [comment]
@greged93 Alright, that's fine. Thanks for reaching out.
