### ISSUE TITLE
feat: replace python devnet by rust devnet (katana) with Kakarot contracts (cairo0) pre-deployed

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#144]
# Feature Request

**Describe the Feature Request**

replace python devnet by rust devnet (katana) with Kakarot contracts (cairo0) pre-deployed

**Describe Preferred Solution**

1. python must not be a dependency on this repo anymore, rust only
2. preferably, katana (rust devnet) should be used in an "independent" local crate that's exposed to the rest of the repo
3. katana should have kakarot main contracts pre-deployed on it. currently katana does not support declare_v1 nor dumps @Eikix will try to enable dumps on devnet

**Comment by bajpai244** [comment]
@Eikix, you can assign this to me, once we have the Katana docker image working, we can use the same here. I can take care of this!

[Here](https://github.com/kkrt-labs/kakarot/issues/589) is the issue for building the Kakarot<>Katana docker image.

**Comment by Eikix** [comment]
Great!
