### ISSUE TITLE
dev: add Starknet Sepolia staging to upgrade.sh

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1453]
**Describe the enhancement request**
We are currently deploying a staging environment on Starknet Sepolia, which will need to be reflected in the upgrade.sh file.

**Comment by Abeeujah** [comment]
Hi, Can I work on this?

**Comment by greged93** [comment]
sorry this is something we need to do ourselves

**Comment by Abeeujah** [comment]
Alright, Thanks for keeping me informed.

**Comment by Eikix** [comment]
What is the status of this?

**Comment by greged93** [comment]
in progress see #1484
