### ISSUE TITLE
dev: add metrics / logs for rejected transactions in our relayer stack 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1467]
**Describe the enhancement request**

cc @greged93 for further scoping

our need: we need to know when transactions are being rejected for wrong nonce by relayers -> it means they are out of sync with their own nonce

**Describe Preferred Solution**

**Comment by greged93** [comment]
I am still a beginner in prometheus, but as far as I understand, we need to:

- [ ] Create a new metric that represents the rejected calls. This can be done using a simple counter [from the prometheus sdk](https://github.com/kkrt-labs/kakarot-rpc/blob/e023ef6a992ff1c52c2df3fd661819428d759543/src/eth_rpc/middleware/metrics.rs#L76) (note that the link is for a `CounterVec`, not a `Counter`, please use a `Counter`).
- [ ] Pass this metric that is now registered to the `AccountManager` structure as he will need to update the metric whenever a call is rejected.
- [ ] In the `AccountManager` loop, in the case where a call is rejected, increment the metric.

**Comment by greged93** [comment]
@Eikix after some talk with the RPC team, can you have a look into our Grafana Kakarot RPC dashboard and verify if it is possible to directly use the available logs in order to build a metric related to the rejected transactions

**Comment by greged93** [comment]
@Eikix can we close this since Karnot was able to make the metrics directly from Grafana?
