### ISSUE TITLE
bug: RPC memory leak

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#1477]
# Bug Report

**Current behavior:**
The RPC is currently leaking some memory over time. Investigate where it comes from (hint: probably comes from the fact that we arent pruning queued transaction in the mempool).

**Other information:**

![photo_2024-10-21 14 37 46](https://github.com/user-attachments/assets/f6cd4e40-2c7b-494f-b4bf-11f2bec7913c)

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/1478
```

**Comment by tcoratger** [comment]
Closed by https://github.com/kkrt-labs/kakarot-rpc/issues/1478
