### ISSUE TITLE
dev: reduce buffer of gas limit multiple from 2x to 1.4x

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#1516]
**Describe the enhancement request**

**Describe Preferred Solution**

In past PRs #1462, we have changed the buffer of gaslimit from 20% to 100%, as we thought the buffer was insufficient. Instead, it was a human error that made it so that the buffer was never applied.

We propose to reduce the buffer back to its original value and a bit more: 40%.

**Comment by ooochoche** [comment]
@Eikix Is this open for contribution?

**Comment by Eikix** [comment]
> @Eikix Is this open for contribution?

Unfortunately it's already done
