### ISSUE TITLE
feat: implement a type wrapper for Event

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#160]
# Feature Request

Implement a type wrapper around starknet-rs `Event` in order to convert to a `Log`.

![image](https://github.com/kkrt-labs/kakarot-rpc/assets/82421016/0e868e05-f43a-4c56-8b9a-f2ab6a8d0465)

```[tasklist]
### Tasks
- [ ] Add a type wrapper around `Event`
- [ ] Create a function `into_eth_log` which takes a implementation of `dyn KakarotClient`
```

**Comment by Eikix** [comment]
you can find some helpers in the main kakarot, i believe @ClementWalter did some scripts in Python to make starknet events fit into ethereum types

**Comment by jobez** [comment]
> you can find some helpers in the main kakarot, i believe @ClementWalter did some scripts in Python to make starknet events fit into ethereum types

https://github.com/jobez/kakarot/blob/main/tests/utils/contracts.py#L118 this is where the magic is happening, i think
