### ISSUE TITLE
dev: remove `fold` where possible

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#166]
Remove the use of `fold` where we are using it to get the first index of a `Vec<FieldElement>`. This is bad practice and should be replaced with another method (could be `get(index)` for example).

Below example of the use of `fold`:
https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/core/src/client/mod.rs#L220
```[tasklist]
### Tasks
- [ ] Find all incorrect instances of the use of `fold`
- [ ] Decide and update to more idiomatic solition
```

**Comment by bajpai244** [comment]
@greged93 I can take this!
