### ISSUE TITLE
feat: modify gas_price route to return gas_price from starknet, using estimateFee route

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#171]
Use this starknet route, with skip validate flag if need for signature

https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_api_openrpc.json#L488

**Comment by greged93** [comment]
Should we not be using this instead?
https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_trace_api_openrpc.json#L41
Also I think the `simulate_transaction` endpoint is currently supported by `starknet-rs` for the [sequencer](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-providers/src/sequencer/mod.rs#L338) but not but the [provider](https://github.com/xJonathanLEI/starknet-rs/blob/master/starknet-providers/src/provider.rs#L16).

**Comment by Eikix** [comment]
I'm not sure! is simulate_transaction the only endpoint that supports the --no-validate flag?

**Comment by greged93** [comment]
That's the only place where I could find the flag

**Comment by Eikix** [comment]
Before starknet-rs implements the simulate_transaction in Provider, we might have to:

- Construct a raw http request pointing to the main gateway that calls simulate_transaction (with a dummy tx) & skip validate flag
- get the gas_price from the result, dump the rest of the response

**Comment by greged93** [comment]
After some research, it seems like too much work to implement the `estimate_gas` using the Sequencer Gateway, given that rust doesn't support specializing, which then requires us to reimplement the whole `EthApiServer` for a RPC server supporting only a `SequencerGatewayProvider`. 
Easiest is to wait for starknet-rs to support the [trace api](https://github.com/starkware-libs/starknet-specs/blob/master/api/starknet_trace_api_openrpc.json#L41).
