### ISSUE TITLE
feat: consolidate and explain mock data

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-rpc#172]
# Feature Request

**Describe the Feature Request**

Conversion between starknet <-> eth types requires concrete instances of each type for testing.

We should organize the values we are using for these instances with explanations for where they come from.

**Describe Preferred Solution**

There should be an importable file where we can add things like

- starknet transactions 
- starknet blocks to their expected ethereum blocks
   - starknet events and their expected translation to ethereum logs

**Describe Alternatives**

**Related Code**

- https://github.com/kkrt-labs/kakarot-rpc/pull/159#pullrequestreview-1490882735
- https://github.com/kkrt-labs/kakarot-rpc/blob/91122e86140515a8e9af97004936b1cb09e02ca7/crates/rpc/tests/rpc.rs#L19

**Comment by Eikix** [comment]
I think this issue is related to #208

**Comment by greged93** [comment]
Indeed, looking at this for the tests for the models folder
