### ISSUE TITLE
bug: Currently Logs on eth_getTransactionReceipt is not returning block data 

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot-rpc#188]
# Bug Report

**Kakarot RPC version:**

**Current behavior:**

Missing information on "eth_getTransactionReceipt" logs field:

**Expected behavior:**

Return all relevant data on Logs

**Steps to reproduce:**

**Related code:**

```
            {
                "address": "0x9d6dc8f529b41e7ef341e1c48a849c00dce4ea10",
                "topics": [
                    "0x000f85617d642704f0a8a5647db56a1492a44de95131dff7326e9349e6362a2c"
                ],
                "data": "0x0000000000000000000000003a35fda41163674a63a4baaeac4605f11ec9295901be84d806d4b02e91e81e9be2f439e759e088c856007eabf341f082c1346e56",
                "blockHash": null,
                "blockNumber": null,
                "transactionHash": null,
                "transactionIndex": null,
                "logIndex": null,
                "removed": false
            },
```

**Other information:**

**Comment by bajpai244** [comment]
So, we do returns logs { you can check [here](https://github.com/kkrt-labs/kakarot-rpc/blob/fd9fbf24da43fdd3dd5fff059dabe0b204758b59/crates/core/src/client/mod.rs#L537) }.

Are you still facing this issue? If yes, then let me know I can investigate as well! otherwise we can close.

**Comment by bajpai244** [comment]
@danilowhk are you still facing this issue?

**Comment by Eikix** [comment]
Has this been fixed @danilowhk

**Comment by danilowhk** [comment]
Working on it

**Comment by danilowhk** [comment]
Closing this issue as it was already fixed with the implementation of the "to_eth_log"

https://github.com/kkrt-labs/kakarot-rpc/blob/1de316620d591d8fe5dad05cea9c011669d16268/crates/core/src/models/event.rs#L30
