### ISSUE TITLE
bug: Fix all the TODOs on "to_eth_transaction" function

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot-rpc#190]
# Bug Report

**Kakarot RPC version:**

**Current behavior:**

Missing many parts for the full EthTransaction type
https://github.com/kkrt-labs/kakarot-rpc/blob/f5b79eac889c2665bc854fadfbe39b7e9e50af98/crates/core/src/models/mod.rs#L349

**Expected behavior:**

Improve real data from the Blockchain

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by Eikix** [comment]
This issue's scope is not well-defined. As such, I've made it a timebox-1day
What does it mean? It means this issue has some amount of research and exploration linked with it.

Developer will have to:

Go through the `to_eth_transaction` in the models folder and investigate each TODO.

And propose in this issue which fields can be fixed.
