### ISSUE TITLE
feat: refactor code base to use convertible starknet event

### ISSUE THREAD

**Issue by jobez** [kkrt-labs/kakarot-rpc#205]
# Feature Request

**Describe the Feature Request**

Refactor code base to use the type wrapper for Event as implemented/described here #160, in particular this section of `transaction_receipt`

https://github.com/kkrt-labs/kakarot-rpc/blob/6888a8183a828ca29d31ed5170aad463f759bceb/crates/core/src/client/mod.rs#L474-L517

Related to #202

**Comment by bajpai244** [comment]
I guess this is a duplicate for #215 , I have pushed #221 which should resolve this as well.

CC: @Eikix
