### ISSUE TITLE
dev: improve `From<Felt252Wrapper>` for `H160`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#213]
The current implementation of `From<Felt252Wrapper> for H160` slices the `felt` in order to store it inside a `H160`. This needs to be updated. Suggestions for update:
- Change the implementation to `TryFrom` and throw an error if the `felt` doesn't fit inside the `H160`.
- Keep `From` and only slice if the `felt` doesn't fix.

Tagging @jobez for discussion.

**Comment by jobez** [comment]
TryFrom approach makes the most sense here, imo.

**Comment by greged93** [comment]
You wan't to work on it?

**Comment by jobez** [comment]
refreshing my memory a bit:

this is the relevant helper code we have, so we should definitely be throwing whenever a felt that is supposed to be standing for an evm address isn't exactly 20 bytes

https://github.com/kkrt-labs/kakarot/blob/1a52997544ed0f00751e5ba10970d7a8c2c51b32/src/utils/utils.cairo#L792-L799
