### ISSUE TITLE
fix: eth_call Erroring when being called by parent contract

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot-rpc#216]
# Bug Report

Currently eth_call endpoint is returning an error when being called by another from another contract

**Kakarot RPC version:**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

Contract being tested

```
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.6;

contract Counter {
    uint256 private count = 0;

    function increment() public {
        count += 1;
    }

    function getCount() public view returns (uint256) {
        return count;
    }
}

contract Caller {
    Counter private counter;

    constructor(address _counterAddress) {
        counter = Counter(_counterAddress);
    }

    function callIncrement() public {
        counter.increment();
    }

    function getCounter() public view returns (uint256) {
        return counter.getCount();
    }
}

```

**Other information:**

**Comment by Eikix** [comment]
What is the status of this @danilowhk ? 
Is this directly linked with https://github.com/kkrt-labs/kakarot/issues/617 ?

Where in the kakarot main SC code can we see that subcalls use get_call_address()?

**Comment by danilowhk** [comment]
Doesnt seem related as the error messages are different.

And from what was tested with @ClementWalter , it seems the issue is on the RPC as when trying to do subcalls directly from python script, the tests passed (even against Madara)

**Comment by Eikix** [comment]
> Doesnt seem related as the error messages are different.
> 
> And from what was tested with @ClementWalter , it seems the issue is on the RPC as when trying to do subcalls directly from python script, the tests passed (even against Madara)


When you say subcalls directly from python scripts, do you mean subcalls, in the context of a "view" call (not invoke) cross contract, on Madara?

**Comment by danilowhk** [comment]
It seems the script is calling as "view":

https://github.com/kkrt-labs/kakarot/blob/baa08057bf24c533748883fe2551a148d6cfcba3/scripts/utils/kakarot.py#L128

This is the code for the script:

```import os

os.environ["STARKNET_NETWORK"] = "madara"
from scripts.utils.kakarot import *

counter = await deploy("PlainOpcodes", "Counter")
plain_opcodes = await deploy("PlainOpcodes", "PlainOpcodes", counter.address)


assert await plain_opcodes.opcodeStaticCall() == await counter.count()
await plain_opcodes.opcodeCall()
await counter.count()
await plain_opcodes.opcodeStaticCall()```

And this is the ABI for the function "opcodeStaticCall" is:

```  {
    "inputs": [],
    "name": "opcodeStaticCall",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },```

**Comment by Eikix** [comment]
Is this is still an ongoing issue?
Is this linked with get_caller issue?

**Comment by danilowhk** [comment]
It seems this is not an issue when calling using directly with forge:

The test for this is the 

uint256 counter_value = plainOpcodes.opcodeStaticCall();

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import "kakarot/PlainOpcodes/Counter.sol";
import "kakarot/PlainOpcodes/PlainOpcodes.sol";

contract PlainOpcodesScript is Script {
    Counter public counter;
    PlainOpcodes public plainOpcodes;

    function run() external {
        uint256 deployerPrivateKey = vm.envUint("EVM_PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);

        counter = new Counter();
        plainOpcodes = new PlainOpcodes(address(counter));

        counter.inc();
        plainOpcodes.opcodeCall();
        plainOpcodes.opcodeCall();
        plainOpcodes.opcodeCall();

        uint256 counter_value = plainOpcodes.opcodeStaticCall();
        address sender_address = counter.getCallerAddress();

        console.logAddress(sender_address);
        console.logUint(counter_value);
        require(counter_value == 4, "Counter should be 4");

        vm.stopBroadcast();
    }
}
```

**Comment by ClementWalter** [comment]
I don't understand the issue, I have no pb running the proposed script (in katana), see
<img width="844" alt="image" src="https://github.com/kkrt-labs/kakarot-rpc/assets/18620296/ccd5b262-010a-4aaa-8692-5d98d8309755">

**Comment by Eikix** [comment]
@ClementWalter @danilowhk  what is the status of this

**Comment by danilowhk** [comment]
Will try again, as get_caller / origin PR was merged

**Comment by Eikix** [comment]
What is the status of this?:)

**Comment by Eikix** [comment]
Closing as subcalls now work properly
