### ISSUE TITLE
feat: Kakarot Rpc method "eth_sendRawTransaction"

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot-rpc#22]
# eth_sendRawTransaction

## Metadatax

- name: sendRawTransaction
- prefix: eth
- state: ⚠️
- [specification](https://github.com/ethereum/execution-apis/blob/02ed29457134d0cf990ca4ad83e8034ed416cb3f/src/eth/submit.yaml#L12)

## Specification Description

Describe the method

### Parameters

- Transaction : bytes

### Returns

- TransactionHash : hash32

## Kakarot Logic

Describe the interaction with Kakarot and/or Starknet.
e.g. "this method does not interact with the kakarot contract or any other starknet contract."

### Kakarot methods

Which Kakarot methods are called?

### Starknet methods

Which Starknet RPC methods are called? e.g. "Would be calling the corresponding `starknet_sendRawTransaction` https://github.com/starkware-libs/starknet-specs/blob/master/starknet_vs_ethereum_node_apis.md"

**Comment by Eikix** [comment]
I can take this one
