### ISSUE TITLE
dev: refactor `KakarotEthApi`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#233]
The current `KakarotEthApi` trait contains some functions that are linked to Starknet and not Ethereum (ex: `submit_starknet_transaction`). Refactor the trait and move these functions to `KakarotStarknetApi`. Also refactor where needed in order to only keep Ethereum function signature i.e. using types from `Reth`.

**Comment by bajpai244** [comment]
@greged93 makes sense, I can take this!
