### ISSUE TITLE
dev: split `decode_signature_and_to_address_from_tx_calldata`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#243]
Split the function `decode_signature_and_to_address_from_tx_calldata` in two, one function that decodes the signature and one function that decodes the to address.

**Comment by danilowhk** [comment]
Do we want to split it? The only places "decode_signature_and_to_address_from_tx_calldata" are used, it needs both the "signature" and "to_address", and if code for both are exactly the same and they are fetched from the exact same struct. If we split we might just do the same "TransactionSigned" / "decoded_tx" twice.

Only this line would be changed while they would be the exact same function:

https://github.com/kkrt-labs/kakarot-rpc/blob/1de316620d591d8fe5dad05cea9c011669d16268/crates/core/src/client/helpers.rs#L115
