### ISSUE TITLE
EthersJs V5 and V6 expected hash failure 

### ISSUE THREAD

**Issue by danilowhk** [kkrt-labs/kakarot-rpc#245]
# Bug Report

Currently, Ethers V5 and V6 pre-calculate the expected hash and return an error if the hash from the EVM chain is different.

Ethersjs is one of the most used libraries and is also used in Hardhat.

Test case:

https://github.com/danilowhk/kakarot-opcode-test/blob/main/kakarot-smart-contracts-scripts/Counter/ethers_counter_script.js

**Kakarot RPC version:**

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**

```
insert short code snippets here
```

**Other information:**

**Comment by Eikix** [comment]
- Open an issue on EtherJS 5 and 6
- Check if the same thing happens in ether-rs, alloy-rs
- Check what is done for Scroll in terms of compat, Polygon zkEVM

**Comment by Eikix** [comment]
What is the status of that

**Comment by Eikix** [comment]
@danilowhk

**Comment by Eikix** [comment]
closing in favour of #323
