### ISSUE TITLE
dev: explore the possibility to use Kakarot's git submodule's foundry.toml file

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#247]
Currently `kakarot-rpc` has its own foundry.toml file,
Let's investigate how complicated it is to use Kakarot's foundry.toml file in the kakarot-rpc core crate flow of integration tests

This issue is meant as an exploratory issue. Spend 1 hour exploring the feasibility and ease of adding this quality of life change. After that time, report on this issue the findings and possible route to implementation.

If implementation is trivial, can also open a PR.

**Comment by jobez** [comment]
Currently we use forge utils for loading the toml from project root:  https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/core/tests/helpers/deploy_helpers.rs#L73

Theoretically we can do something fancier with 
https://github.com/foundry-rs/foundry/blob/bf56869aaf61e58be1dd4058159268c4529d73f6/config/src/utils.rs#L147

This would allow us to derive more than one possible path that a given contract could exist and search across both/all available.

**Comment by jobez** [comment]
#257 brought this into being, through the power of anime
