### ISSUE TITLE
bug: Unable to deploy kakaswap

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#251]
# Bug Report

**Kakarot RPC version:**

Latest main

**Current behavior:**

When:
- running madara as starknet backend
- running kakarot-rpc
- running kakaswap deploy script targetting kakarot-rpc

Then:
- fails at the first `sendRawTransaction` with internal server error

Note:
- with added `dbg!` macro it works, so we suspect a distributed systems issues/delays, etc.

**Other information:**

To test the issue, you need to:
1. madara main and `cargo run --bin madara --release -- --dev`
2. kakarot main and `STARKNET_NETWORK=madara make deploy`
3. kakarot-rpc main and `cargo run --bin kakarot-rpc`
4. kakaswap main and `RPC_URL=http://127.0.0.1:3030 python scripts/deploy.py`

Note: this is note an issue about making kakaswap actually working, it's an issue regarding kakarot-rpc failing when trying to deploy "something" that happened to me when trying to deploy kakaswap.

**Comment by jobez** [comment]
What is considered a fix to this bug? 

Is the ask to have a reliable, turn key solution to kakaswap deployment? Perhaps dockerized?

**Comment by Eikix** [comment]
Let's close this issue, as we are no longer using kakaswap in our test flow
