### ISSUE TITLE
Use forge script to test deployment in the RPC

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#265]
## Why

Currently, we need to use an external EVM project (like kakaswap) to test a regular deployment process on Kakarot.
This creates an extra unnecessary complexity.

## What

Add a forge script to deploy the basic solidity contracts that we already use in the Kakarot EVM testing

## How

[] update kakarot path
[] add forge lib
[] create a simple script that mimics the deployment of Counter + PlainOpcodes found in `test_plain_opcodes.py`
[] run and see!

**Comment by jobez** [comment]
wdyt of this possible flow: https://github.com/kkrt-labs/kakarot-rpc/issues/253#issuecomment-1625086554

the flow of these kinds of tests could look like 
- use testsequencer to be the starknet provider that plugs into kakarot client, 
- construct a kakarot rpc and 
- then 'call out' to a forge script within a test.

**Comment by ClementWalter** [comment]
Now that the `TestSequencer` seems fine (can they merge the branch? is there any blocker?) it seems ok to me to go with it for integration testing.

**Comment by Eikix** [comment]
What is the status of this issue?
It appears we have successfully added forge in our flow, could close this issue
wdyt @ClementWalter
