### ISSUE TITLE
Pin rev for any github dependency

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#267]
## Why

We have faced a numerous of unexpected "not our business" bugs because of github deps that are not pinned ot a given rev.

## What

Remove all weakly defined reps: a dep **must** point to a given rev

## How

Look for all the deps in all the Cargo.toml files and add `rev=` if missing

**Comment by Eikix** [comment]
Confirming all git dependencies point to a specific rev
