### ISSUE TITLE
feat: Deploy a corresponding EOAccount when the RPC receives a tx from a funded but not deployed EOA

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#281]
# Feature Request

**Describe the Feature Request**

In the EVM, there is no sense of deploying an EOA. All the addresses are always existing, eventually with no code.
Currently, when processing a signed tx, the RPC needs to use the deployed EOAccount corresponding to the EVM EOA used to send the tx.
This account needs to be deployed already, which doesn't make sense for the EVM world.

**Describe Preferred Solution**

When broadcasting a transaction, the RPC should check if the corresponding contract already exist and if not, send a `DEPLOY_ACCOUNT` transaction first.

Not that since the EOA tries to send a tx, it's assumed that it has ETH (otherwise not possible to send a tx). So the RPC doesn't need to send a deploy account tx and the deployed account will pay for the fees.

**Comment by bajpai244** [comment]
Hello @ClementWalter , I can take this :)

**Comment by Eikix** [comment]
- We want the user's resulting starknet address from that deployment to be equal to `kakarot.compute_starknet_address(user_evm_address)`

**Comment by bajpai244** [comment]
The agreed upon approach as of now is:
- User makes a call to RPC with an EOA
- RPC checks if the corresponding Starknet account exists or not
- If it doesn’t then it sends the `deploy account transaction` to the sequencer, which should automatically take care of deploying this account and taking the fee from the account.

![image](https://github.com/kkrt-labs/kakarot-rpc/assets/41180869/82e61dd1-af9e-4835-aac1-c2d76bd2aea9)

For this PR to be made, firstly a PR for [this](https://github.com/kkrt-labs/kakarot/issues/668) issue has to be merged on Kakarot main repo.
