### ISSUE TITLE
dev: make `simulate_transaction` agnostic to provider

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#306]
**Describe the enhancement request**
The current implementation of `simulate_transaction` will fail if the provider is not a `SequencerGatewayProvider`. This line will throw an error:
```
let mut url = self
            .network
            .gateway_url()?
            .join("simulate_transaction")
            .map_err(|e| EthApiError::FeederGatewayError(format!("gateway url parsing error: {:?}", e)))?;
```
when getting the gateway url:
```
pub fn gateway_url(&self) -> Result<Url, ConfigError> {
        match self {
            Network::Mainnet => Ok(Url::parse("https://alpha-mainnet.starknet.io/feeder_gateway/").unwrap()),
            Network::Goerli1 => Ok(Url::parse("https://alpha4.starknet.io/feeder_gateway/").unwrap()),
            Network::Goerli2 => Ok(Url::parse("https://alpha4-2.starknet.io/feeder_gateway/").unwrap()),
            _ => Err(ConfigError::InvalidNetwork(format!("Network {:?} is not supported for gateway url", self))),
        }
    }
```
Goal would be to update the current implementation in order make the function call pass for every type of `Network`.

**Comment by Eikix** [comment]
What is the current blocker for this issue? That tracing api is implemented by rpc clients?
I think it'd help to have a sense of what the dependencies are for each issue with low to medium prio for codebase improvement.

**Comment by greged93** [comment]
Main blocker is that currently starknet-rs Provider trait does not implement the trace api spec. We could build the json-rpc query ourself and send it manually but that would also require handling the `send` since the `JsonRpcClient` from starknet-rs doesn't expose a way to send raw queries.

**Comment by Eikix** [comment]
Alright! Let's wait until starknet-rs provider supports trace api

**Comment by Eikix** [comment]
This is currently blocked by starknet-rs roadmap
