### ISSUE TITLE
bug: Metamask UI stuck during transfer

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#321]
# Bug Report

**Kakarot RPC version: 28a29a45fd00d22d767844da40bceafb2bd20a72**

**Current behavior:**

Metamask transfer of native ETH doesn't work, the behaviour can be observed while using the RPC with both Katana and Madara. It seems to be some issue with gas estimation as the UI is stuck there and the button to proceed with the transaction is not clickable.

**Expected behavior:**

Metamask UI should work and we should be able to proceed with the transfer in Metamask itself.

**Steps to reproduce:**

- Run Katana/Madara { with Kakarot deployed on it }
- Run RPC
- Import the EOA defined in `.env.example` in the project root
- Try to transfer Eth to some other account.

**Comment by Eikix** [comment]
Is this still happening @bajpai244 ?

**Comment by bajpai244** [comment]
@Eikix we can close this, it is fixed so I am moving ahead and closing it.
