### ISSUE TITLE
bug: ethers js fails while doing transfer of native token

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#323]
# Bug Report

**Kakarot RPC version: 28a29a45fd00d22d767844da40bceafb2bd20a72**

**Current behavior:**

When we create an Ether js [wallet](https://docs.ethers.org/v4/api-wallet.html), and try to make a transfer of native token to some other address, then it fails with the following error:
`error -> Error: @TODO: the returned hash did not match`

**Expected behavior:**

The behaviour should pass without any error.

**Steps to reproduce:**

- Run katana or madara with Kakarot deployed on it
- Run the Kakarot RPC over the above
- Run the following javascript code { fill the placeholders for URL and private key }:
```javascript
const {Wallet, JsonRpcProvider, parseEther} = require("ethers")

async function nativeTokenTransfer () {
    const targetUrl = "put_kakarot_rpc_url_here";
    const privateKey = "put_private_key"

    const provider = new JsonRpcProvider(targetUrl);
    const wallet = new Wallet(privateKey, provider);
    const wallet2 = Wallet.createRandom(provider);

    console.log("balance before ----->", await provider.getBalance(wallet.address));

    await wallet.sendTransaction({to: wallet2.address, value: parseEther("0.1")});

    console.log("balance after ----->", await provider.getBalance(wallet.address));
}

async function main() {
  await nativeTokenTransfer();
}

main();
```
**Other information:**

- The native token transfer works, I can see the balance of the source account go down.
- [This](https://github.com/ethers-io/ethers.js/blob/main/lib.esm/providers/abstract-provider.js#L719) is the ethers js code from where the error seems to be originating.
- The reason as of now seems to because we use starknet transaction hashes, while Ethereum use keccak hash over serialized ethereum transaction.

Here is a detailed log of the error:
```shell
 Error: @TODO: the returned hash did not match
    at JsonRpcProvider.broadcastTransaction (/Users/harshbajpai/Desktop/Projects/kakarot-rpc/benchmarking/node_modules/ethers/lib.commonjs/providers/abstract-provider.js:723:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Wallet.sendTransaction (/Users/harshbajpai/Desktop/Projects/kakarot-rpc/benchmarking/node_modules/ethers/lib.commonjs/providers/abstract-signer.js:185:16)
```

**Comment by bajpai244** [comment]
We have opened an issue to ethers js [here](https://github.com/ethers-io/ethers.js/issues/4233).

**Comment by Eikix** [comment]
what is the status of this @bajpai244

**Comment by bajpai244** [comment]
@Eikix, we still have an issue open here for this on ethers js, it hasn't been resolved in the library -> https://github.com/ethers-io/ethers.js/issues/4233

**Comment by Eikix** [comment]
Fixed by Indexer migration
