### ISSUE TITLE
feat: define all methods of Net Api and implement them.

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#330]
# Feature Request

- As of now we don't define and implement all methods of the Net Api.
- [Here](https://github.com/paradigmxyz/reth/blob/main/crates/rpc/rpc-api/src/net.rs) are all methods defined by the API

Define all remaining methods and implement them.

**Comment by bajpai244** [comment]
@Eikix this is a low priority, non blocking task, it was made to document this for future and as a good first contribution issue, it not taken by any contributor I will take it and implement it when we have time to address this.

**Comment by aniketpr01** [comment]
@bajpai244 can I take this?

**Comment by greged93** [comment]
assigned
