### ISSUE TITLE
feat: define all Token methods of Alchemy Api and implement them.

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#331]
# Feature Request

Currently we don't define and implement all Alchemy Token endpoints.
- [Here](https://docs.alchemy.com/reference/token-api-quickstart) are all alchemy token endpoints
- Define and implement the remaining token endpoints.

----

Note: It seems like Token endpoints is just a section of [other APIs](https://docs.alchemy.com/reference) that might be required to support alchemy SDK, we should investigate about other methods as well in future { not super high priority as of now. }

If you can find other Apis like the token api that we can implement here for alchemy, then feel free to add those methods in the PR resolving this issue as well.
```[tasklist]
### Tasks
- [ ] define all alchemy token methods in eth-rpc/src/api/alchemy_api.rs
- [ ] implement all alchemy token mehtods in eth-rpc/src/servers/alchemy_rpc.rs
```

**Comment by erik-rt** [comment]
Mind if I tackle this? If I understand, we'll need to add the models for metadata and allowance and then implement the KakarotEthApi and AlchemyApiServers traits with the additional functionality, correct?

**Comment by greged93** [comment]
This is up for grabs
