### ISSUE TITLE
feat: load a genesis state for Kakarot, on Madara

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#343]

**Comment by Eikix** [comment]
Linked to https://github.com/keep-starknet-strange/madara/pull/913

**Comment by Eikix** [comment]
what is the status of this @greged93

**Comment by greged93** [comment]
We can now load a genesis state into Madara, so we need to make one for Kakarot and then simply use it when running Madara.

**Comment by greged93** [comment]
done as per PR #396
