### ISSUE TITLE
feat: bundle into Madara a genesis state that has: a Kakarot system (kakarot main SC, block registry, eoa, proxy, contract) deployed and an initial state as per hive conformance tests

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#348]

**Comment by Eikix** [comment]
Spec needed @greged93 
Depends on #345 #343

**Comment by ftupas** [comment]
Currently, [here](https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/conformance-test-utils/src/hive/genesis.rs#L68-L117) we load the Kakarot system into the Madara genesis. Setting the class hashes, pre-deploying the contracts and setting initial state This is coming from this [pr](https://github.com/kkrt-labs/kakarot-rpc/pull/396)
