### ISSUE TITLE
feat: using the docker file that has Madara + Kakarot + hive genesis state + kakarot-RPC, launch hive and run tests.

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#352]

**Comment by Eikix** [comment]
world boss

**Comment by Eikix** [comment]
@ftupas what is the status of this?

**Comment by ftupas** [comment]
So technically we are now able to use the Dockerfile to run the hive tests but they are not passing due to the EOA funding issue 😥 Should we close this and add the debugging issues to the epic?
