### ISSUE TITLE
investigate: investigate how docker works in hive to prepare for hive conformance test dockerized

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#353]
https://github.com/ethereum/hive/blob/master/docs/overview.md

Understand how hive instrumentalizes docker

**Comment by ftupas** [comment]
Kindly assign, thank you

**Comment by Eikix** [comment]
https://excalidraw.com/#room=37daef30945727080660,4MK0NFVw6X3mT_wO-fC9fw

**Comment by ftupas** [comment]
I've documented my findings here https://www.notion.so/kakarotlabs/Hive-Testing-859f6b3f539c42aa8b52c656830592b2
