### ISSUE TITLE
feat: Add a HEALTHCHECK in the madara dockerfile

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/kakarot-rpc#357]
# Feature Request

**Describe the Feature Request**

See https://docs.docker.com/engine/reference/builder/#healthcheck
In order for other services to know when the RPC is ready

**Comment by ClementWalter** [comment]
@ftupas you may want to do this!

**Comment by ftupas** [comment]
> @ftupas you may want to do this!

Looks like it's been added already for Madara [here](https://github.com/keep-starknet-strange/madara/pull/915), but I don't see for [Katana](https://github.com/dojoengine/dojo/blob/main/Dockerfile), should I make a pr there?
