### ISSUE TITLE
feat: add a healthcheck in katana docker image for best practices

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#360]
# Feature Request

**Describe the Feature Request**

Let's try to create a health check in katana

**Describe Preferred Solution**

**Comment by Eikix** [comment]
Copy structure of healthcheck in madara

**Comment by ftupas** [comment]
Created the issue https://github.com/dojoengine/dojo/issues/682

**Comment by Eikix** [comment]
Closing as your PR got merged!! Ggggggg 🥕
