### ISSUE TITLE
dev: create `EthereumErc20` abstraction

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#366]
**Describe the enhancement request**
Similar to `KakarotContract` abstraction, create an `EthereumErc20` which will perform any calls related to a Kakarot token contract.

**Describe Preferred Solution**

**Comment by Eikix** [comment]
I think we can call it EthereumErc20 since its counterpart is StarknetErc20?
otherwise lgtm ;D

**Comment by Eikix** [comment]
My bad this is dumb I think! We can simply use ether-rs for this and any type of Ethereum side abstraction, granted we have an ABI!

**Comment by Eikix** [comment]
My bad! ether-rs can only be used from outside the rpc world
