### ISSUE TITLE
Continue reading on Hive and investigate Oak's changes on Madara for genesis JSON file

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#408]
```[tasklist]
### Tasks
- [x] Investigate Hive further
- [x] Investigate Oak changes on Madara
```

Results down below

**Comment by greged93** [comment]
Oak changes have been merged, it is now possible to pull all genesis files from a URL or using the `madara_path` when running the node. This can thus allow us to have all genesis files locally and point to them using the madara path flag.
See PR [here](https://github.com/keep-starknet-strange/madara/pull/974).
