### ISSUE TITLE
feat: add missing storage values in the the Madara genesis

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#447]
When loading the genesis file to Madara, there are some storage variables that are not populated. For example [`bytecode_len_`](https://github.com/kkrt-labs/kakarot/blob/7825c0055baef2f95e3e1cefe417cd8a65ce3ace/src/kakarot/accounts/contract/library.cairo#L22). Since it's not set `bytecode` doesn't return anything even if the bytecode is set in the right storage key

```shell
❌
# starkli call 0x033e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 bytecode --rpc http://0.0.0.0:9944
[
    "0x0000000000000000000000000000000000000000000000000000000000000000"
]

❌
# starkli call 0x033e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 bytecode_len --rpc http://0.0.0.0:9944
[
    "0x0000000000000000000000000000000000000000000000000000000000000000"
]

✅
# starkli storage 0x33e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 0x1199149d8c9cc006b3ee80a7c76b1224e90f98969bfd45e3dd1a566e210647e --rpc http://0.0.0.0:9944
0x0000000000000000000000000000000060606040526000357c01000000000000
```

These are some of the missing storage values (not exhaustive)
- Contract Account
    - [x] [`bytecode_len_`](https://github.com/kkrt-labs/kakarot/blob/7825c0055baef2f95e3e1cefe417cd8a65ce3ace/src/kakarot/accounts/contract/library.cairo#L22)
    - [x] [`is_initialized`](https://github.com/kkrt-labs/kakarot/blob/7825c0055baef2f95e3e1cefe417cd8a65ce3ace/src/kakarot/accounts/contract/library.cairo#L30)
    - [x] [`evm_address`](https://github.com/kkrt-labs/kakarot/blob/7825c0055baef2f95e3e1cefe417cd8a65ce3ace/src/kakarot/accounts/contract/library.cairo#L34)
    - [x] [`Ownable_owner`](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/access/ownable/library.cairo#L23C6-L23C19)
    - [x] [`ERC20_allowances`](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/token/erc20/library.cairo#L52C6-L52C22)
- EOA
    - [x] [`evm_address`](https://github.com/kkrt-labs/kakarot/blob/40fc24ab352a0a5a73863410358097c037312f67/src/kakarot/accounts/eoa/library.cairo#L16)
    - [x] [`kakarot_address`](https://github.com/kkrt-labs/kakarot/blob/40fc24ab352a0a5a73863410358097c037312f67/src/kakarot/accounts/eoa/library.cairo#L20)
    - [x] [`is_initialized`](https://github.com/kkrt-labs/kakarot/blob/40fc24ab352a0a5a73863410358097c037312f67/src/kakarot/accounts/eoa/library.cairo#L24)
    - [x] [`ERC20_allowances`](https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/openzeppelin/token/erc20/library.cairo#L52C6-L52C22)

**Comment by greged93** [comment]
Following have been tested:

- Contract account
  - `bytecode_len`: `starkli call 0x033e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 bytecode_len --rpc http://localhost:9944`
  - `is_initialized`: `starkli storage 0x033e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 0x2d69c78cf84ceed4a129696a2f63409add4f93acdd0d38f1fbdc815b0a2d82 --rpc http://localhost:9944`
  - `evm_address`: `starkli storage 0x033e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 0x3f43484c2593529120e2eb76b9577bc1f9d00c0d456831a7ff2a28a39b43f86 --rpc http://localhost:9944`
  - `Owner_ownable`: `starkli storage 0x033e9f1e5084a5f64858670cea0907648132a3959ef5084f5000702463a67678 0x2bd557f4ba80dfabefabe45e9b2dd35db1b9a78e96c72bc2b69b655ce47a930 --rpc http://localhost:9944`
  - `ERC20_allowances`: `starkli storage 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7  0x65b2ab5de9420190642186e15901e351e3e3d918e890e723c1a1c1332c7234e --rpc http://localhost:9944` and `starkli storage 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7  0x65b2ab5de9420190642186e15901e351e3e3d918e890e723c1a1c1332c7234f --rpc http://localhost:9944`

- EOA
  - `is_initialized`: `starkli storage 0xa919c43c0cee2ff22a8b1d7d9caed171c644e769c9bc60929c49ef303300b8 0x2d69c78cf84ceed4a129696a2f63409add4f93acdd0d38f1fbdc815b0a2d82 --rpc http://localhost:9944`
  - `evm_address`:  `starkli storage 0xa919c43c0cee2ff22a8b1d7d9caed171c644e769c9bc60929c49ef303300b8 0x3f43484c2593529120e2eb76b9577bc1f9d00c0d456831a7ff2a28a39b43f86 --rpc http://localhost:9944`
  - `kakarot_address`:  `starkli storage 0xa919c43c0cee2ff22a8b1d7d9caed171c644e769c9bc60929c49ef303300b8 0x293202b7c8f619d642dd127233d82b8ae5f38ac7f4f6dc24b76ab1a7382d671 --rpc http://localhost:9944`
  - `ERC20_allowances`: `starkli storage 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7  0x31915fb846ee51027c9cb231fbc775b2b106709c946e9abb875eba0ce476dfd --rpc http://localhost:9944` and `starkli storage 0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7  0x31915fb846ee51027c9cb231fbc775b2b106709c946e9abb875eba0ce476dfe --rpc http://localhost:9944`
