### ISSUE TITLE
dev: investigate new `y_parity` field of `Signature`

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#468]
**Describe the enhancement request**

With reth dependency getting bumped to https://github.com/paradigmxyz/reth/commit/34b68deedf401624de09fd24d63361be8f4f9987, `Signature` has an additional field of `y_parity`. For now in #466 , we are setting it to `None`.

```rust
#[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
pub struct Signature {
    /// The R field of the signature; the point on the curve.
    pub r: U256,
    /// The S field of the signature; the point on the curve.
    pub s: U256,
    // TODO: change these fields to an untagged enum for `v` XOR `y_parity` if/when CLs support it.
    // See <https://github.com/ethereum/go-ethereum/issues/27727> for more information
    /// For EIP-155, EIP-2930 and Blob transactions this is set to the parity (0 for even, 1 for
    /// odd) of the y-value of the secp256k1 signature.
    ///
    /// For legacy transactions, this is the recovery id
    ///
    /// See also <https://ethereum.github.io/execution-apis/api-documentation/> and <https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionbyhash>
    pub v: U256,
    /// The y parity of the signature. This is only used for typed (non-legacy) transactions.
    #[serde(default, rename = "yParity", skip_serializing_if = "Option::is_none")]
    pub y_parity: Option<Parity>,
}
```

**Describe Preferred Solution**

Investigate what would be the the right value for `y_parity` and make the necessary changes

**Comment by Eikix** [comment]
> **Describe the enhancement request**
> 
> 
> 
> 
> 
> 
> 
> With reth dependency getting bumped to https://github.com/paradigmxyz/reth/commit/34b68deedf401624de09fd24d63361be8f4f9987, `Signature` has an additional field of `y_parity`. For now in #466 , we are setting it to `None`.
> 
> 
> 
> ```rust
> 
> #[derive(Debug, Clone, PartialEq, Eq, Hash, Default, Serialize, Deserialize)]
> 
> pub struct Signature {
> 
>     /// The R field of the signature; the point on the curve.
> 
>     pub r: U256,
> 
>     /// The S field of the signature; the point on the curve.
> 
>     pub s: U256,
> 
>     // TODO: change these fields to an untagged enum for `v` XOR `y_parity` if/when CLs support it.
> 
>     // See <https://github.com/ethereum/go-ethereum/issues/27727> for more information
> 
>     /// For EIP-155, EIP-2930 and Blob transactions this is set to the parity (0 for even, 1 for
> 
>     /// odd) of the y-value of the secp256k1 signature.
> 
>     ///
> 
>     /// For legacy transactions, this is the recovery id
> 
>     ///
> 
>     /// See also <https://ethereum.github.io/execution-apis/api-documentation/> and <https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionbyhash>
> 
>     pub v: U256,
> 
>     /// The y parity of the signature. This is only used for typed (non-legacy) transactions.
> 
>     #[serde(default, rename = "yParity", skip_serializing_if = "Option::is_none")]
> 
>     pub y_parity: Option<Parity>,
> 
> }
> 
> ```
> 
> 
> 
> **Describe Preferred Solution**
> 
> 
> 
> Investigate what would be the the right value for `y_parity` and make the necessary changes
> 
> 
> 
> 
> 
> 

Is this still up to date?

**Comment by Eikix** [comment]
Alright, we can wait for implementing this
This reminds me / makes me doubt about the ability of Kakarot to read typed tx
