### ISSUE TITLE
dev: migrate to `cross` framework for cross compilation

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#474]
**Describe the enhancement request**

In continuation of #472 and #473 , the problem arises from cross compilation. Some teams were experiencing the same issues with [bindgen](https://github.com/FuelLabs/fuel-core/pull/342) in which they had to manually add [`sysroot`](https://github.com/rust-lang/rust-bindgen/issues/1229#issuecomment-707950665) for it to work.

**Describe Preferred Solution**

It would be good to migrate to [cross](https://github.com/cross-rs/cross) framework for cross compilation

**Comment by Eikix** [comment]
> **Describe the enhancement request**
> 
> 
> 
> 
> 
> 
> 
> In continuation of #472 and #473 , the problem arises from cross compilation. Some teams were experiencing the same issues with [bindgen](https://github.com/FuelLabs/fuel-core/pull/342) in which they had to manually add [`sysroot`](https://github.com/rust-lang/rust-bindgen/issues/1229#issuecomment-707950665) for it to work.
> 
> 
> 
> **Describe Preferred Solution**
> 
> 
> 
> It would be good to migrate to [cross](https://github.com/cross-rs/cross) framework for cross compilation
> 
> 
> 
> 
> 
> 

Is this still up to date?:)

**Comment by ftupas** [comment]
Yeah I still think it would be good to migrate to [`cross`](https://github.com/cross-rs/cross) eventually, this way we don't need to manually fix these problems 🙂 I'll add a low prio label to the issue
