### ISSUE TITLE
dev: use official Madara image/binary

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#477]
**Describe the enhancement request**

Currently, we're using a forked image of [madara](https://github.com/kkrt-labs/kakarot-rpc/blob/0e772e5959140ca1bc43b22d349b9830dcd77857/crates/hive-utils/Dockerfile#L3) to run our hive tests. This allows us to load custom genesis assets i.e. hive genesis, kakarot contracts, etc. when we initialize Madara. There is this [pr](https://github.com/keep-starknet-strange/madara/pull/1018) in Madara to enable this feature and once it's merged, we should migrate to this.

**Describe Preferred Solution**

Investigate and migrate to the official Madara image. Make sure that the genesis is loaded properly

**Comment by d-roak** [comment]
Hey, we just merged the big PR, lmk (on tg) if you need help integrating it in your codebase
