### ISSUE TITLE
bug: bytecode for `Account` trait returns length as well 

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#498]
# Bug Report

**Kakarot RPC version:** [a8bd946](https://github.com/kkrt-labs/kakarot-rpc/commit/a8bd946b437b5a3ce2988a97cdf00d58f15c6641)

**Current behavior:**
The `bytecode` function from the `Account` trait will return the bytecode length included in the bytecode.

**Expected behavior:**
The `bytecode` function should just return the bytecode and remove the length.

**Steps to reproduce:**
- Deploy bytecode to a contract and set the bytecode length.
- Create a `KakarotAccount` object.
- Call `bytecode` on it.

**Related code:**
https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/accounts/contract/library.cairo#L123
https://github.com/kkrt-labs/kakarot-rpc/blob/a8bd946b437b5a3ce2988a97cdf00d58f15c6641/crates/core/src/contracts/account.rs#L41-L44

**Comment by Eikix** [comment]
Is this still up for grab? I think it is important

**Comment by greged93** [comment]
still available yes
