### ISSUE TITLE
dev: Move Alchemy Token API endpoints to new Alchemy API trait

### ISSUE THREAD

**Issue by erik-rt** [kkrt-labs/kakarot-rpc#507]
**Describe the enhancement request**

The [Alchemy Token API](https://docs.alchemy.com/reference/token-api-quickstart) endpoints being developed in #339 are currently defined in the `KakarotEthApi` trait. Since these endpoints aren't actually a part of the Eth API, these should be moved to a new Alchemy-centric trait.

**Describe Preferred Solution**

Define a new trait such as `KakarotAlchemyApi` and move the Alchemy Token API endpoint implementations to this new trait.

**Comment by greged93** [comment]
Can we close this @Eikix ?
