### ISSUE TITLE
feat: add release for `kakarot-rpc`

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#530]
# Feature Request

**Describe the Feature Request**

- We should be doing pre-release for the following:
  - kakarot-rpc
  - dump-katana

This will enable being able to consumes them on the CI jobs.

**Describe Preferred Solution**

- Add a github action which runs on every PR and does builds and publishes pre-release pushes a pre-release of these binaries.

**Comment by Eikix** [comment]
Adding the low-priority label to this issue right now, as we've agreed to start by clone and building from source in the Kakarot CI first.
