### ISSUE TITLE
dev: refactor derivation for `compiled_kakarot_path` and `compiled_solidity_path`

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#542]
**Describe the enhancement request**

In the current structure of the RPC, we look `compiled_kakarot_path` and `compiled_solidity_path` relative to the root of the current project structure.

We need the ability to be able to pass absolute paths, so that when on CI, we can configure the test utils to use directories outside the Kakarot RPC for kakarot and solidity builds.

**Describe Preferred Solution**

- add a new envrioment variable `FOUNDRY_OUTPUT_PATH` which defaults to `./lib/kakarot/tests/integration/solidity_contracts/build` so that RPC can be configured to take solidity builds from outside the root of the repo.
- change to the following strategy for checking these paths:
   - Firstly search for the path as an absolute path.
   - If this fails, then search for the path relative to the project root.

The above should allow all good DX features the current flow has alongwith the option to configure the RPC to use builds from outside its repo root.

**Comment by bajpai244** [comment]
I am putting here another approach I have in mind which should make the current assumptions easier and the codebase cleaner.

## A common `build` directory

I am suggesting having a common `build` directory at the root of the RPC { auto-generated at runtime }. This will allow our make commands to just have an extra step of moving whatever they build to these directories.

The code can have a simple assumption, that there the following two directores in the `build` directory at the root:
- kakarot { contains kakarot build  }  
- solidity-contracts { contains build of solidity contracts }

If they are not present, we can throw an error!

This will make the code way simpler, with no need for extra environment variables, and extending this on CI will be easier as well, where we can simply move the builds to these directories!

**Comment by jobez** [comment]
Can you walk me through how this would work? You still need an environment variable to have the system know where the artifacts are coming from, right?

**Comment by jobez** [comment]
This sounds good!

When one runs the tests locally, we just assume the kakarot source of artifacts is the submodule and copy it over?

**Comment by bajpai244** [comment]
@jobez we would no longer need this strategy, yesterday we had a small call with Clement, and we realized a way to make the current flow of the ef-tests simpler.

But, yeah, the strategy that I was discussing was that of assuming a common build directory for the whole kakarot-rpc-codebase, and searching for all required builds there.

**Comment by bajpai244** [comment]
This issue is no longer relevant, and hence closing this.
