### ISSUE TITLE
Avoid reassignment of `test_environment` when we deploy evm contracts

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#567]
Currently, we instantiate a `KakarotTestEnvironmentContext` here

https://github.com/kkrt-labs/kakarot-rpc/blob/0f4a260c8e8e77f637b0930052015f34c87ce533/crates/test-utils/src/deploy_helpers.rs#L704-L705

When we deploy evm contracts, we do a re-assignment then we return this mutation of its `Self`

https://github.com/kkrt-labs/kakarot-rpc/blob/0f4a260c8e8e77f637b0930052015f34c87ce533/crates/test-utils/src/deploy_helpers.rs#L713-L716

We would want to avoid this re-assignment

**Comment by bajpai244** [comment]
@ftupas I am fixing this.
