### ISSUE TITLE
Remove `Network` from `KakarotClient`

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/kakarot-rpc#570]
Currently, we use `Network` for [`simulate_transaction`](https://github.com/kkrt-labs/kakarot-rpc/blob/93493495f755b658655cc889b274373a0c410449/crates/core/src/client/mod.rs#L732) because some networks were not supporting it.

https://github.com/kkrt-labs/kakarot-rpc/blob/93493495f755b658655cc889b274373a0c410449/crates/core/src/client/mod.rs#L740-L745

Investigate if Madara and Katana have this functionality so we can remove `Network` from `KakarotClient` since we will not need to check the url anymore

**Comment by ftupas** [comment]
Looked into both Madara and Katana and currently they don't implement `simulate_transaction`. The other approach is a bit more complicated i.e. make a wrapper and implement `gateway_url` and `provider_url`

**Comment by Eikix** [comment]
What is the status of this @greged93
