### ISSUE TITLE
bug: remove cyclic deps

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#572]
# Bug Report

**Current behavior:**
Cyclic deps between kakarot rpc test utils and kakarot rpc core breaks rust-analyzer. It is now loading a long time and it sometimes doesn't allow you to jump to structure, function, trait definitions.

**Expected behavior:**
Rust-analyzer should not be broken.

**Steps to reproduce:**
Open current repo, wait a while and try a couple of times to jump to definitions. It should fail after a while.

**Other information:**
This seems to be a known issue: https://github.com/rust-lang/rust-analyzer/issues/3390

**Comment by Eikix** [comment]
fixed!
