### ISSUE TITLE
feat: add health check path

### ISSUE THREAD

**Issue by apoorvsadana** [kkrt-labs/kakarot-rpc#641]
# Feature Request

**Describe the Feature Request**

Having a health check path is generally helpful when deploying with Cloud providers. The current RPC only supports `POST` and `OPTIONS` requests and AWS only allows GET requests for Health checks in target groups. I am assuming this might also be the case with other providers.

**Describe Preferred Solution**

Add a GET `/health` endpoint which

- Checks if the RPC_URL is still online and returns a boolean. Sample response
```
{ "rpc_online": true }
```

**Comment by TAdev0** [comment]
Hi @Eikix, m

**Comment by TAdev0** [comment]
Hello @apoorvsadana  @Eikix ,
I spent a few times trying to figure out what should be done concretely. This is my first time dealing with infra.
Could you provide me a slightly more detailed explanation about how to handle this health check? Should i add a function in `eth_rpc.rs` ?
Thank you.

**Comment by Eikix** [comment]
> Hello @apoorvsadana @Eikix , I tried a few times to figure out what should be done concretely. This is my first time dealing with infra. Could you provide me a slightly more detailed explanation about how to handle this health check? Should i add a function in `eth_rpc.rs` ? Thank you.

Hey @TAdev0 thanks for taking the time.
I haven't given this a lot of thought, but we'd probably need to add a file in the eth-rpc crate, where all the different servers are declared: eth-api, alchemy-api etc., we could add our own there, with its Health method.

Let's see what @apoorvsadana suggests, but the method should live outside of the ethereum rpc spec, but as an "exposed" method -> the only way is to add a new server

**Comment by TAdev0** [comment]
implementing
```
  async fn health(&self) -> Result<bool> {
        Ok(true)
    }
 ```
 would return true only if the RPC is true

**Comment by TAdev0** [comment]
@Eikix  ok i'll try to do that.
What is the core difference between API and Servers folders? This feature doesn't modification in the server folder files?

**Comment by Eikix** [comment]
> @Eikix ok i'll try to do that. Thank you for clarification !

I'm def no expert either at infra / network,
You may want to check how other clients  and full node implement their health endpoint

**Comment by TAdev0** [comment]
it seems that :
- reth Net API only exposes `version`, `peer_count` and `is_listening` and doesn't have a health check. 
- reth Eth API doesn't have a health check either

@apoorvsadana  did you think of any special way to implement it?

**Comment by Eikix** [comment]
> it seems that :
> 
> * reth Net API only exposes `version`, `peer_count` and `is_listening` functions and doesn't have a health check.
> * reth Eth API doesn't have a health check either
> 
> @apoorvsadana did you think of any special way to implement it?

Then I guess we can add a file in API, in order to not "break" net api

**Comment by TAdev0** [comment]
@Eikix  this issue can be closed, PR linked already merged
