### ISSUE TITLE
dev: delete assert_helpers 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#648]
**Describe the enhancement request**

As per https://github.com/kkrt-labs/kakarot-rpc/discussions/646, I want to delete assert_helpers.

Delete their occurrences and replace where applicable.

**Comment by bhavyagosai** [comment]
i cannot find `assert_helpers`, is it already and can be closed?

**Comment by Eikix** [comment]
> i cannot find `assert_helpers`, is it already and can be closed?
> 
> 

I'll check again tomorrow, chances are I deleted it in my latest pr
