### ISSUE TITLE
feat: add a complete docker compose file for apibara integration, with mongodb

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#730]
# Feature Request

**Describe the Feature Request**

presently, in the feat/apibara_integration branch, we start a DNA indexer plugged into the starknet node that locally runs (katana)

let's add two more parts in the architecture:
- the kakarot rpc apibara indexer https://github.com/kkrt-labs/kakarot-indexer
- a mongodb local instance

**Comment by greged93** [comment]
Can this be closed @Eikix ?
