### ISSUE TITLE
dev: add a fuzzer for the mongo db 

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#748]
**Describe the enhancement request**

In order to expand and improve the current tests, it would be interesting to have a fuzzer for the various fields of the blocks and transactions.

Check the file in `test-utils/mongo/mod.rs` for more details.

**Comment by tcoratger** [comment]
Can work on this, I'm currently on my way to propose a PR with a `MongoFuzzer` structure, implementing the fuzzer logic for header, transaction and receipt fields.
