### ISSUE TITLE
bug: getBlockByNumber returns null all the time

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#753]
# Bug Report

In the current version of the RPC,

```
❯ curl -X POST -H "Content-Type: application/json" -d '{
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x1e0", true],
    "id": 1
}' http://192.168.1.17:3030
```

```
{"jsonrpc":"2.0","result":null,"id":1}%
```

**Current behavior:**

Start the docker compose (make katana-rpc-up)

Try to fill the blocks -> make benchmark-katana

Then 
```
 curl -X POST -H "Content-Type: application/json" -d '{
    "jsonrpc": "2.0",
    "method": "eth_blockNumber",     
    "params": [],       
    "id": 1
}' http://127.0.0.1:3030
```

**Expected behavior:**

Should give the block with the accurate data.

Additionally, over multiple minutes, the block number is stuck at the same height, even tthough the chain progresses.

**Comment by greged93** [comment]
Can this be closed @Eikix ?
