### ISSUE TITLE
benchmark: benchmark indexing time

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#798]
We need to benchmark how much time it takes for a transaction to happen on the Starknet app chain where Kakarot is running vs it to be indexed by the RPC.

This will allow us to understand how much the delay looks like and what the experience will look like for applications that rely heavily on data.

**Comment by greged93** [comment]
closing this, I find that such an issue needs more scoping if we really want to tackle it. Also I believe we can get an idea of this delay by checking the logs
