### ISSUE TITLE
feat: automatic deployment of EOA

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/kakarot-rpc#802]
# Feature Request

**Describe the Feature Request**

If account x sends to some eth to account y, then in the current approach, y would have to deploy an EOA before being able to use its account!

We should solve this allow automatic deployment of EOA from our end!

**Describe Preferred Solution**

We have to discuss this!

**Comment by greged93** [comment]
@bajpai244 can we close this? now that we have automatic deployment of EOA's in Kakarot thanks to eni

**Comment by bajpai244** [comment]
sure!
