### ISSUE TITLE
dev: make setup failed

### ISSUE THREAD

**Issue by imotai** [kkrt-labs/kakarot-rpc#905]
**Describe the enhancement request**

 Encounter `cannot stat 'build/ssj/contracts_Precompiles.contract_class.json': No such file or directory` when running setup
**Describe Preferred Solution**

rename `contracts_Precompiles.contract_class.json` to `contracts_Cairo1Helpers.contract_class.json`

**Comment by Eikix** [comment]
Thanks for spotting this!
