### ISSUE TITLE
feat: change block tag logic from SN pending = EVM latest to SN pending = EVM pending, SN latest = EVM latest

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#907]
# Feature Request

**Describe the Feature Request**

Change block tag logic from SN pending = EVM latest to SN pending = EVM pending, SN latest = EVM latest
Context:
In Kakarot Sepolia SN appchain, block time is now ~12s. We can proceed with normal EVM behavior -> pending blocks are pending, latest blocks are latest.

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] modify conversion methods for EVM block tag to SN block tag
- [ ] make sure that this modification is compatible with the dev setup of Katana / local Kakarot devnet
```

**Comment by greged93** [comment]
closest with #934 and https://github.com/kkrt-labs/kakarot-indexer/pull/41
