### ISSUE TITLE
dev: remove deref for new type pattern

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#910]
**Describe the enhancement request**

i got told off by @tdelabro about `Deref` 

```rust

impl Deref for Felt252Wrapper {
    type Target = FieldElement;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl DerefMut for Felt252Wrapper {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}
```

**This trait should be implemented on smart pointers / pointers only, not new type pattern.**
The language intended way is to use from/into 🤮

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] For Felt252Wrapper, remove Deref/DerefMut
- [ ] Fix red squiggles and add .into() a bit everywhere, thanks Timothee....
```

**Comment by Eikix** [comment]
Additional documentation: https://doc.rust-lang.org/std/ops/trait.Deref.html

**Comment by greged93** [comment]
Also going through the docs:
ˋˋˋ
In general, deref traits should not be implemented if:

the deref implementations could fail unexpectedly; or
the type has methods that are likely to collide with methods on the target type; or
committing to deref coercion as part of the public API is not desirable.
ˋˋˋ

I don't see any reason why it would fail, we aren't implementing any methods on the wrapper type and we are actually aiming for deref coercion in order to remove unnecessary from's and into's from all over the code. Would keep the code as is in order to keep the code lighter.

**Comment by tdelabro** [comment]
```
If we wanted the new type to have every method the inner type has, implementing the Deref trait (discussed in Chapter 15 in the [“Treating Smart Pointers Like Regular References with the Deref Trait”](https://doc.rust-lang.org/book/ch15-02-deref.html#treating-smart-pointers-like-regular-references-with-the-deref-trait) section) on the Wrapper to return the inner type would be a solution.
```

In this specific case, it may be okay. But still, it feels super weird to use: One type is expected as an argument, I give another, but it still compiles. It breaks every expectation I have when writing rust code.

https://stackoverflow.com/questions/45086595/is-it-considered-a-bad-practice-to-implement-deref-for-newtypes
Heated debate ^^^

I think it is indeed allowed by the language, and nothing bad will happen during the execution, but it is a bad practice.
All of Rust design is about being explicit about type, and this just wipes it all. Feels bad.

**Comment by tdelabro** [comment]
I would also say, it is kinda okay if it is just for your internal private types, and you never leak this wrapper type in any public API. Then it's your internal impl problem, as long as it is working I don't really care.
But do this on a public type that I'm expected to manipulate, I become crazy :)

**Comment by tdelabro** [comment]
Found someone nicely explaining my point here: https://rust-unofficial.github.io/patterns/anti_patterns/deref.html#deref-polymorphism

**Comment by Eikix** [comment]
> I think both points of view are valid. Normally we use `deref` and `derefMut` only when there is a wrapper. It depends on repos and standards.
> 
> * For example, on reth, this practice is widely encouraged:
>   
>   * [feat(primitives): add `Receipts` to encapsulate `Vec<Vec<Option<Receipt>>` paradigmxyz/reth#4626 (comment)](https://github.com/paradigmxyz/reth/pull/4626#discussion_r1328480685)
>   * [Implement `Deref` and `DerefMut` for `StateProviderDatabase` paradigmxyz/reth#6538](https://github.com/paradigmxyz/reth/pull/6538)
>   * [feat(access-list): refactor and add some utils to `AccessList` paradigmxyz/reth#6144](https://github.com/paradigmxyz/reth/pull/6144)
> * But there are indeed repos where this way of deferring is considered as an unwanted complexity of language.
> 
> I think we need to define a standard for this repo and stick to it, there is no problem for me if we say to ourselves that we should not use `deref` and `derefMut` for these use cases. What do you think?

Thanks for the context!

How about:
- for private wrapper types that are a simple answer to the trait orphan rule, e.g. Felt252Wrapper, we keep Deref and DerefMut
- for anything else: public facing API & anything other than a (smart) pointer, we don't use those traits

**Comment by greged93** [comment]
> for anything else: public facing API & anything other than a (smart) pointer, we don't use those traits

So in RPC it's ok to use `Deref` for all the wrapper type right? since we expose a eth rpc, none of our internal types should be public.

**Comment by Eikix** [comment]
> > for anything else: public facing API & anything other than a (smart) pointer, we don't use those traits
> 
> So in RPC it's ok to use `Deref` for all the wrapper type right? since we expose a eth rpc, none of our internal types should be public?

I would tend to think so, granted the wrapper type is unsurprising as you mentioned! i.e.
1. never remotely collides with underlying methods or traits
