### ISSUE TITLE
dev: add retesteth as a local runnable script

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#920]
**Describe the enhancement request**

we need a easy way to assert the rpc behaves correctly, e.g. after a kakarot upgrade or bump

**Describe Preferred Solution**

make it possible to run retesteth on the rpc repo

**Comment by Eikix** [comment]
also, need to make sure we can use it, spend some time investigating

**Comment by greged93** [comment]
can you develop a little the goal here? retesteth is a way to run the ef-tests via RPC, but we already run the ef-tests on the Kakarot repo, so you want to run a part of the ef-tests here?

**Comment by Eikix** [comment]
> can you develop a little the goal here? retesteth is a way to run the ef-tests via RPC, but we already run the ef-tests on the Kakarot repo, so you want to run a part of the ef-tests here?

I think when we had this conversation, we wanted to assert that the RPC was working well, i.e. the best to do it are the ef-tests, so we wanted to use the RPC as it is to run the ef-tests

**Comment by greged93** [comment]
Hmmmm do you think we can close? I'm not sure it would be possible to run the ef-tests on rpc
