### ISSUE TITLE
dev: to have robust staging ingration stage, build fuzzed diff testing

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#921]
**Describe the enhancement request**

we need to test the staging environnement: kakarot on starknet sepolia before deploying to prod when making updates to the network 

**Describe Preferred Solution**

run anvil and kakarot system in parallel, bombard with random txs, assert chains are the same after

idea: can run anvil in fork mode?

otherwise: find technique to never collide storages

**Comment by hhamud** [comment]
@greged93 can I have this one?

**Comment by greged93** [comment]
@tcoratger I think we can close this as done no?

**Comment by tcoratger** [comment]
Yes let us close
