### ISSUE TITLE
dev: batch RPC requests linked to storage queries

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#940]
**Describe the enhancement request**
The json RPC standard allows to send a batch of request (see [link](https://sajya.github.io/docs/batch/) and [link](https://docs.actian.com/openroad/6.2/index.html#page/ServerRef/JSON-RPC_Batch_Requests.htm)). This would allow us to batch the requests to the node for storage requests in the context of a call for example. 

**Describe Preferred Solution**
- Verify batch request is available on Juno.
- Verify it is possible to build and send a batch request in Rust.
- Explore the different hotpoints on our code where batching would improve the latency.
- Implement a wrapper type in order to perform batch requests to a starknet json rpc.
- Batch calls where possible

# Links
- https://github.com/foundry-rs/foundry/blob/master/crates/anvil/rpc/src/request.rs#L58

**Comment by hhamud** [comment]
can I take this one? @greged93  @tcoratger

**Comment by greged93** [comment]
hey @hhamud this is quite a complicated issue so probably better not if you don't have a lot of experience with our stack. This is actually still blocked for now, waiting for this https://github.com/xJonathanLEI/starknet-rs/pull/600 PR on starknet-rs.

**Comment by Eikix** [comment]
What is the status of this one @greged93

**Comment by greged93** [comment]
I think batch calls were merged in starknet-rs 3 weeks ago so this is unblocked and open for contribution

**Comment by greged93** [comment]
Might need to check if this is supported on the release we are using for starknet-rs

**Comment by adrienlacombe** [comment]
done [here](https://github.com/xJonathanLEI/starknet-rs/pull/653)

**Comment by Eikix** [comment]
as I understand this, we are now able to move forward with this issue? cc @greged93

**Comment by greged93** [comment]
I looked into this but actually there isn't really a place where we need this now, we could have used this before when we were querying two storage slots or two nonces but we don't anymore

**Comment by Eikix** [comment]
> I looked into this but actually there isn't really a place where we need this now, we could have used this before when we were querying two storage slots or two nonces but we don't anymore

how do we query storage slots? we don't need to query them two by two?

**Comment by greged93** [comment]
No via the `storage` from the account contracts.

**Comment by greged93** [comment]
We could actually use this in the retrieval of all the nonces for the relayers.
