### ISSUE TITLE
dev: in the next release of reth, replace our util implementation of RPC transactions to Reth Primitives transaction to reth's TryFrom new trait

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-rpc#960]
**Describe the enhancement request**

in the next release of reth, replace our util implementation of RPC transactions to Reth Primitives transaction to reth's TryFrom new trait

The PR: https://github.com/paradigmxyz/reth/pull/7551

**Describe Preferred Solution**

- first check that the PR https://github.com/paradigmxyz/reth/pull/7551 solves our problem
- then, if so, delete the associated code in rpc_transaction_to_primitive and replace

**Comment by Eikix** [comment]
Note that this is blocked until https://github.com/paradigmxyz/reth/pull/7551 is incorporated in a release

**Comment by tcoratger** [comment]
For your information https://github.com/kkrt-labs/kakarot-rpc/pull/1004 merge should unlock the situation here.

**Comment by edisontim** [comment]
Hello, can I take this one?

**Comment by tcoratger** [comment]
> Hello, can I take this one?

Assigned
