### ISSUE TITLE
dev: use `Default` implementation for `GenesisJson`

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#968]
**Describe Preferred Solution**

After next release of Dojo and integration of https://github.com/dojoengine/dojo/pull/1830, the 

```rust
GenesisJson {
    // other fields
    .. Default::default()
}
```

pattern can be used to replace the following verbose construction:

https://github.com/kkrt-labs/kakarot-rpc/blob/d2128cf23e8981284e577cb00dcbbf9464f3beb1/src/test_utils/katana/genesis.rs#L320-L339

**Comment by 0xicosahedron** [comment]
can i work on this once release is done?

**Comment by tcoratger** [comment]
> can i work on this once release is done?

Sure just assigned
