### ISSUE TITLE
dev: use reth `TryFrom` impl to convert blocks and headers

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#970]
**Describe Preferred Solution**

After next reth release and integration of https://github.com/paradigmxyz/reth/pull/7660#event-12476448733

- `rpc_to_primitive_header` method 

https://github.com/kkrt-labs/kakarot-rpc/blob/d2128cf23e8981284e577cb00dcbbf9464f3beb1/src/models/block.rs#L71-L104

can be removed and replaced by reth native `TryFrom` implementation call.

- `rpc_to_primitive_block` method

https://github.com/kkrt-labs/kakarot-rpc/blob/d2128cf23e8981284e577cb00dcbbf9464f3beb1/src/models/block.rs#L106-L136

can be removed and replaced by reth native `TryFrom` implementation call.

**Comment by bhavyagosai** [comment]
Hey! I think I can take this up if its up for grabs?

**Comment by tcoratger** [comment]
> Hey! I think I can take this up if its up for grabs?

Sure just assigned

**Comment by tcoratger** [comment]
For your information https://github.com/kkrt-labs/kakarot-rpc/pull/1004 merge should unlock the situation here.

**Comment by bhavyagosai** [comment]
yes yes I saw the release has happened, working on it right now 😅
