### ISSUE TITLE
dev: update prometheus related crates

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#971]
**Describe Preferred Solution**

At the moment, all the crates related to Prometheus are not up to date versions:

https://github.com/kkrt-labs/kakarot-rpc/blob/d2128cf23e8981284e577cb00dcbbf9464f3beb1/Cargo.toml#L153-L157

especially `hyper` for which version `0.14.16` is 3 years old. We should update these crates using up to date versions and update the required code accordingly.

**Comment by KeneePatel** [comment]
Can I pick this up?

**Comment by KeneePatel** [comment]
Feel free to assign me @tcoratger

**Comment by tcoratger** [comment]
> Feel free to assign me @tcoratger 

Sure just assigned.

**Comment by KeneePatel** [comment]
Hey @tcoratger,

So I tried updating the dependencies. There's nothing wrong with updating the prometheus or the governor, and the latest version is just 0.0.3 version ahead. And the pin-project-lite is already up-to-date.

However, hyper is having big and breaking changes. I had a look at the [mod.rs](https://github.com/kkrt-labs/kakarot-rpc/blob/d2128cf23e8981284e577cb00dcbbf9464f3beb1/src/prometheus_handler/mod.rs) file. The changes are with Body, Client, Server and Service (with its related helper functions).

There is no problem with the Client as it is having a drop-in replacement (with the help of [hyper-util](https://docs.rs/hyper-util/latest/hyper_util/) crate, adding another dependency), but updating the other parts has me in a squint. So, how do you suggest me to continue on the issue.

Putting out this link for reference: https://hyper.rs/guides/1/upgrading/

**Comment by tcoratger** [comment]
Hey @KeneePatel,

Yes, you're right, that was the goal of this issue. In fact we don't want to depend (or at least minimally) on very old versions of the crates. And here this was the case with version `0.14.16` which is largely outdated and must be updated.

As a result, this is reflected in several important changes in the crate given the age of the current version.

As you pointed out with your upgrading reference guide, I think that you will need to use the following util crate as part of the code was deported there after v1:
- `hyper-util` in order to produce the `Builder` that replaces the old `Server::builder`
- `http-body-util` in order to replace the old `Body`

For the imports, should be something along:
```rust
use bytes::Bytes;
use http_body_util::combinators::BoxBody;
use http_body_util::Full;
use hyper::body::Body;
use hyper::http::StatusCode;
use hyper::service::service_fn;
use hyper::Request;
use hyper::Response;
use hyper_util::server::conn::auto::Builder;
```

For the `request_metrics` function, I would do something along:

```rust
async fn request_metrics(
     req: Request<hyper::body::Incoming>,
     registry: Registry,
) -> Result<Response<BoxBody<Bytes, Infallible>>, Error> {
     if req.uri().path() == "/metrics" {
         let metric_families = registry.gather();
         let mut buffer = vec![];
         let encoder = TextEncoder::new();
         encoder.encode(&metric_families, &mut buffer).unwrap();

         Response::builder()
             .status(StatusCode::OK)
             .header("Content-Type", encoder.format_type())
             .body(Full::new(Bytes::from(buffer)))
             .map_err(Error::Http)
     } else {
         Response::builder()
             .status(StatusCode::NOT_FOUND)
             .body(Full::new(Bytes::from("Not found.")))
             .map_err(Error::Http)
     }
}
```
And finally you need to modify `init_prometheus_with_listener` in order to build the server using the `hyper_util::server::conn::auto::Builder` I would say. Feel free to suggest anything else (this is just an initial proposal and of course we are opened to better ones) and open a draft PR so that we can start from there.

You can probably find a reference for that here https://github.com/hyperium/hyper/blob/226305d0fc78ab780aa5a1084e013a3b0a39e4d8/examples/graceful_shutdown.rs or in other similar examples of the repo.

**Comment by KeneePatel** [comment]
Thank you so much @tcoratger ser for the much needed guidance; however, I am still facing a bit of issue. please have a look at the PR for more details.
