### ISSUE TITLE
dev: derive arbitrary for stored data

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#973]
**Describe Preferred Solution**

 
 After the next release of reth, once https://github.com/alloy-rs/alloy/pull/458 and https://github.com/alloy-rs/alloy/pull/449 are integrated, we can remove the hand made implementation of stored data in the RPC:

- `StoredHeader`
https://github.com/kkrt-labs/kakarot-rpc/blob/21bfa9eed0477fe6778288e6ca1617d92b26f295/src/eth_provider/database/types/header.rs#L13-L45

- `StoredTransactionReceipt`
https://github.com/kkrt-labs/kakarot-rpc/blob/21bfa9eed0477fe6778288e6ca1617d92b26f295/src/eth_provider/database/types/receipt.rs#L19-L63

- `StoredTransaction`
https://github.com/kkrt-labs/kakarot-rpc/blob/21bfa9eed0477fe6778288e6ca1617d92b26f295/src/eth_provider/database/types/transaction.rs#L26-L72

and simply derive the implementation using the alloy existing implementations and derivations. 

We must also take care in the mock database to restrict the values when necessary to avoid having out of range values for the tests (if the primitive value is restricted to `u64`, then the arbitrary value should fit into it).

**Comment by greged93** [comment]
@tcoratger I think we can close this no?

**Comment by tcoratger** [comment]
@greged93 Yes closed by #1015.
