### ISSUE TITLE
dev: improve logging using json formatting

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#981]
**Describe the enhancement request**
In order to make logs processing easier, update the current tracing implementation to use JSON formatting. 

See below tracing from DNA:
![image](https://github.com/kkrt-labs/kakarot-rpc/assets/82421016/b49d2c89-9c78-497f-9eaf-bf154c253b3c)

This can be achieved using RUST_LOG_FORMAT: json in the environment for DNA.

**Comment by bhavyagosai** [comment]
Checked out how they are doing it for DNA. Can you consider assigning it to me?

**Comment by greged93** [comment]
hey @bhavyagosai yeah sorry, little involved with multiple blocks in our infra, will be easier if I take this
