### ISSUE TITLE
dev: use `with_chain_id` for `CfgEnv`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/kakarot-rpc#990]
**Describe the enhancement request**
Once [this PR](https://github.com/bluealloy/revm/pull/1327) is merged in `revm`, add the function `with_chain_id` in order to set the chain id of the config.

This needs to be updated in `tracing/mod.rs` in the `new` function of the `Tracer`.

**Comment by jaipaljadeja** [comment]
hey is it up for grabs? i would like to take this. : )

**Comment by tcoratger** [comment]
> hey is it up for grabs? i would like to take this. : )

Assigned

**Comment by Pycomet** [comment]
If this is still available, can i take it @tcoratger ?

**Comment by tcoratger** [comment]
> If this is still available, can i take it @tcoratger ?

Hey @Pycomet sorry but this issue is blocked until next release of reth when https://github.com/bluealloy/revm/pull/1327 is included. And this issue is already assigned but feel free to pick another one and if you don't find one, stay tuned for the next one we release, happy to help :)

**Comment by Josh-121** [comment]
please assign
