### ISSUE TITLE
dev: replace `rpc_to_ec_recovered_transaction` by `try_from`

### ISSUE THREAD

**Issue by tcoratger** [kkrt-labs/kakarot-rpc#998]
**Describe Preferred Solution**

Following the merge of https://github.com/paradigmxyz/reth/pull/7752 and after the next release of reth where this change will be included, we can remove `rpc_to_ec_recovered_transaction` method from our codebase

https://github.com/kkrt-labs/kakarot-rpc/blob/a9e0b7817d47e65b598a69b69b3cf37af80004af/src/models/transaction.rs#L89-L106

and simply replace the call to `rpc_to_ec_recovered_transaction` by a `try_from` with proper error handling.

**Comment by PabloVillaplana** [comment]
Hey @tcoratger, I would like to contribute to this issue 👀.

Another question: Do you have a Telegram or Discord channel where I can ask you some questions?

**Comment by tcoratger** [comment]
> Hey @tcoratger, I would like to contribute to this issue 👀.
> 
> Another question: Do you have a Telegram or Discord channel where I can ask you some questions?

Just assigned, feel free to ask your questions here (I think this is the place where they will be best treated) or you can DM me on Twitter if needed, can give you my Telegram.

**Comment by tcoratger** [comment]
Maybe you will have a blocker before this one is integrated https://github.com/paradigmxyz/reth/pull/7882#pullrequestreview-2023117213 as found in https://github.com/kkrt-labs/kakarot-rpc/pull/1016
